<?php

/**
 * Реестр каналов уведомлений и рассылок (справочник для админки /users).
 */
return [
    'channels' => [
        'modal' => [
            'icon' => 'bi-window-stack',
            'color' => 'primary',
            'title' => 'Users notify channel modal',
            'description' => 'Users notify channel modal desc',
        ],
        'telegram' => [
            'icon' => 'bi-telegram',
            'color' => 'info',
            'title' => 'Users notify channel telegram',
            'description' => 'Users notify channel telegram desc',
        ],
        'email_event' => [
            'icon' => 'bi-envelope-exclamation',
            'color' => 'email',
            'title' => 'Users notify channel email event',
            'description' => 'Users notify channel email event desc',
        ],
        'email_service' => [
            'icon' => 'bi-envelope-paper',
            'color' => 'secondary',
            'title' => 'Users notify channel email service',
            'description' => 'Users notify channel email service desc',
        ],
    ],

    'modals' => [
        [
            'key' => 'telegram-connect',
            'title' => 'Users notify modal telegram connect',
            'description' => 'Users notify modal telegram connect desc',
            'queue_priority' => 10,
            'pages' => 'Users notify modal telegram connect pages',
        ],
        [
            'key' => 'monitoring-schedule-paid',
            'title' => 'Users notify modal monitoring schedule',
            'description' => 'Users notify modal monitoring schedule desc',
            'queue_priority' => 20,
            'pages' => 'Users notify modal monitoring schedule pages',
        ],
    ],

    'modules' => [
        [
            'slug' => 'profile',
            'title' => 'Telegram admin module profile',
            'route' => 'profile.index',
            'route_fragment' => 'telegram',
            'modal' => false,
            'telegram' => true,
            'email_event' => false,
            'email_service' => true,
            'cron' => null,
            'hint' => 'Users notify module profile hint',
        ],
        [
            'slug' => 'backlink',
            'title' => 'Telegram admin module backlink',
            'route' => 'backlink',
            'admin_route' => 'backlink.config',
            'modal' => false,
            'telegram' => true,
            'email_event' => true,
            'email_service' => false,
            'cron' => 'GET /api/backlink/scan-broken-links',
            'hint' => 'Telegram admin notify backlink',
        ],
        [
            'slug' => 'site-monitoring',
            'title' => 'Telegram admin module site monitoring',
            'route' => 'site.monitoring',
            'admin_route' => 'site.monitoring.config',
            'modal' => false,
            'telegram' => true,
            'email_event' => true,
            'email_service' => false,
            'cron' => 'domain monitoring cron',
            'hint' => 'Telegram admin notify site monitoring',
        ],
        [
            'slug' => 'domain-information',
            'title' => 'Telegram admin module domain information',
            'route' => 'domain.information',
            'admin_route' => 'domain.information.config',
            'modal' => false,
            'telegram' => true,
            'email_event' => true,
            'email_service' => false,
            'cron' => 'domain information cron',
            'hint' => 'Telegram admin notify domain information',
        ],
        [
            'slug' => 'meta-tags',
            'title' => 'Telegram admin module meta tags',
            'route' => 'meta-tags.index',
            'modal' => false,
            'telegram' => true,
            'email_event' => false,
            'email_service' => false,
            'cron' => 'MetaTags cron',
            'hint' => 'Telegram admin notify meta tags',
        ],
        [
            'slug' => 'cluster',
            'title' => 'Telegram admin module cluster',
            'route' => 'cluster',
            'modal' => false,
            'telegram' => true,
            'email_event' => false,
            'email_service' => false,
            'cron' => null,
            'hint' => 'Telegram admin notify cluster',
        ],
        [
            'slug' => 'monitoring-limits',
            'title' => 'Telegram admin module monitoring limits',
            'route' => 'monitoring.projects.get',
            'modal' => false,
            'telegram' => true,
            'email_event' => true,
            'email_service' => false,
            'cron' => null,
            'hint' => 'Telegram admin notify monitoring limits',
        ],
        [
            'slug' => 'monitoring-positions',
            'title' => 'Users notify module monitoring positions',
            'route' => 'monitoring.projects.get',
            'modal' => true,
            'telegram' => false,
            'email_event' => false,
            'email_service' => false,
            'cron' => null,
            'hint' => 'Users notify module monitoring positions hint',
        ],
        [
            'slug' => 'news',
            'title' => 'Users notify module news',
            'route' => 'news',
            'modal' => false,
            'telegram' => false,
            'email_event' => false,
            'email_service' => false,
            'cron' => null,
            'hint' => 'Users notify module news hint',
            'badge_only' => true,
        ],
        [
            'slug' => 'auth',
            'title' => 'Users notify module auth',
            'route' => 'login',
            'modal' => false,
            'telegram' => false,
            'email_event' => false,
            'email_service' => true,
            'cron' => null,
            'hint' => 'Users notify module auth hint',
        ],
    ],

    /**
     * Простые правила для шапки страницы /admin/notifications.
     */
    'rules' => [
        [
            'icon' => 'bi-telegram',
            'color' => 'info',
            'title' => 'Users notify rule telegram title',
            'body' => 'Users notify rule telegram body',
        ],
        [
            'icon' => 'bi-envelope-exclamation',
            'color' => 'email',
            'title' => 'Users notify rule email title',
            'body' => 'Users notify rule email body',
        ],
        [
            'icon' => 'bi-window-stack',
            'color' => 'primary',
            'title' => 'Users notify rule modal title',
            'body' => 'Users notify rule modal body',
        ],
    ],

    /**
     * Каждое реальное оповещение: когда → кому → каналы → пример текста.
     * Ключи title/trigger/audience/example_* — строки для __() в ru.json.
     */
    'events' => [
        [
            'slug' => 'modals',
            'title' => 'Users notify events module modals',
            'route' => null,
            'items' => [
                [
                    'id' => 'modal-telegram-connect',
                    'title' => 'Users notify event modal tg title',
                    'trigger' => 'Users notify event modal tg trigger',
                    'audience' => 'Users notify event modal tg audience',
                    'channels' => ['modal'],
                    'tariff' => 'Users notify tariff all',
                    'cron' => null,
                    'example_modal' => 'Users notify event modal tg example',
                    'code_ref' => 'TelegramConnectPromptComposer',
                ],
                [
                    'id' => 'modal-monitoring-schedule',
                    'title' => 'Users notify event modal schedule title',
                    'trigger' => 'Users notify event modal schedule trigger',
                    'audience' => 'Users notify event modal schedule audience',
                    'channels' => ['modal'],
                    'tariff' => 'Users notify tariff free only',
                    'cron' => null,
                    'example_modal' => 'Users notify event modal schedule example',
                    'code_ref' => 'User::shouldShowMonitoringSchedulePaidPrompt',
                ],
            ],
        ],
        [
            'slug' => 'profile',
            'title' => 'Telegram admin module profile',
            'route' => 'profile.index',
            'route_fragment' => 'telegram',
            'items' => [
                [
                    'id' => 'profile-telegram-test',
                    'title' => 'Users notify event profile tg test title',
                    'trigger' => 'Users notify event profile tg test trigger',
                    'audience' => 'Users notify event profile tg test audience',
                    'channels' => ['telegram'],
                    'tariff' => 'Users notify tariff all',
                    'cron' => null,
                    'example_telegram' => 'Users notify event profile tg test example',
                    'code_ref' => 'TelegramBot::sendTestNotify',
                ],
                [
                    'id' => 'profile-password-reset',
                    'title' => 'Users notify event profile password title',
                    'trigger' => 'Users notify event profile password trigger',
                    'audience' => 'Users notify event profile password audience',
                    'channels' => ['email_service'],
                    'tariff' => 'Users notify tariff all',
                    'cron' => null,
                    'example_email' => 'Users notify event profile password example',
                    'code_ref' => 'RegisterPasswordEmail',
                ],
            ],
        ],
        [
            'slug' => 'backlink',
            'title' => 'Telegram admin module backlink',
            'route' => 'backlink',
            'admin_route' => 'backlink.config',
            'items' => [
                [
                    'id' => 'backlink-telegram-summary',
                    'title' => 'Users notify event backlink tg title',
                    'trigger' => 'Users notify event backlink tg trigger',
                    'audience' => 'Users notify event backlink tg audience',
                    'channels' => ['telegram'],
                    'tariff' => 'Users notify tariff all tg',
                    'cron' => 'GET /api/backlink/scan-broken-links',
                    'example_telegram' => 'Users notify event backlink tg example',
                    'code_ref' => 'CroneController → User::sendBrokenLinkProjectTelegram',
                ],
                [
                    'id' => 'backlink-email-link',
                    'title' => 'Users notify event backlink email title',
                    'trigger' => 'Users notify event backlink email trigger',
                    'audience' => 'Users notify event backlink email audience',
                    'channels' => ['email_event'],
                    'tariff' => 'Users notify tariff paid email',
                    'cron' => 'GET /api/backlink/scan-broken-links',
                    'example_email' => 'Users notify event backlink email example',
                    'code_ref' => 'BrokenLinkNotification',
                ],
            ],
        ],
        [
            'slug' => 'site-monitoring',
            'title' => 'Telegram admin module site monitoring',
            'route' => 'site.monitoring',
            'admin_route' => 'site.monitoring.config',
            'items' => [
                [
                    'id' => 'site-mon-broken',
                    'title' => 'Users notify event site broken title',
                    'trigger' => 'Users notify event site broken trigger',
                    'audience' => 'Users notify event site broken audience',
                    'channels' => ['telegram', 'email_event'],
                    'tariff' => 'Users notify event site broken tariff',
                    'cron' => 'GET /api/domain-monitoring/check-link-crone/{timing}',
                    'example_telegram' => 'Users notify event site broken tg example',
                    'example_email' => 'Users notify event site broken email example',
                    'code_ref' => 'DomainMonitoring::sendNotifications',
                ],
                [
                    'id' => 'site-mon-repaired',
                    'title' => 'Users notify event site repaired title',
                    'trigger' => 'Users notify event site repaired trigger',
                    'audience' => 'Users notify event site repaired audience',
                    'channels' => ['telegram', 'email_event'],
                    'tariff' => 'Users notify event site broken tariff',
                    'cron' => 'GET /api/domain-monitoring/check-link-crone/{timing}',
                    'example_telegram' => 'Users notify event site repaired tg example',
                    'example_email' => 'Users notify event site repaired email example',
                    'code_ref' => 'DomainMonitoring::sendNotifications',
                ],
                [
                    'id' => 'site-mon-repeat',
                    'title' => 'Users notify event site repeat title',
                    'trigger' => 'Users notify event site repeat trigger',
                    'audience' => 'Users notify event site broken audience',
                    'channels' => ['telegram', 'email_event'],
                    'tariff' => 'Users notify event site broken tariff',
                    'cron' => 'GET /api/domain-monitoring/check-link-crone/{timing}',
                    'example_telegram' => 'Users notify event site broken tg example',
                    'example_email' => 'Users notify event site broken email example',
                    'code_ref' => 'DomainMonitoring::sendNotifications (repeat)',
                ],
            ],
        ],
        [
            'slug' => 'domain-information',
            'title' => 'Telegram admin module domain information',
            'route' => 'domain.information',
            'admin_route' => 'domain.information.config',
            'items' => [
                [
                    'id' => 'domain-dns-changed',
                    'title' => 'Users notify event domain dns title',
                    'trigger' => 'Users notify event domain dns trigger',
                    'audience' => 'Users notify event domain dns audience',
                    'channels' => ['telegram', 'email_event'],
                    'tariff' => 'Users notify event domain dns tariff',
                    'cron' => 'GET /api/domain-information/check-domain-crone/',
                    'example_telegram' => 'Users notify event domain dns tg example',
                    'example_email' => 'Users notify event domain dns email example',
                    'code_ref' => 'DomainInformation::sendNotifications',
                ],
                [
                    'id' => 'domain-expiration',
                    'title' => 'Users notify event domain expire title',
                    'trigger' => 'Users notify event domain expire trigger',
                    'audience' => 'Users notify event domain expire audience',
                    'channels' => ['telegram', 'email_event'],
                    'tariff' => 'Users notify event domain dns tariff',
                    'cron' => 'GET /api/domain-information/check-domain-crone/',
                    'example_telegram' => 'Users notify event domain expire tg example',
                    'example_email' => 'Users notify event domain expire email example',
                    'code_ref' => 'DomainInformation::sendNotifications',
                ],
            ],
        ],
        [
            'slug' => 'meta-tags',
            'title' => 'Telegram admin module meta tags',
            'route' => 'meta-tags.index',
            'items' => [
                [
                    'id' => 'meta-tags-changed',
                    'title' => 'Users notify event meta title',
                    'trigger' => 'Users notify event meta trigger',
                    'audience' => 'Users notify event meta audience',
                    'channels' => ['telegram'],
                    'tariff' => 'Users notify tariff all tg',
                    'cron' => 'MetaTags cron (6/12/24 ч)',
                    'example_telegram' => 'Users notify event meta tg example',
                    'code_ref' => 'MetaTags cron → meta-tags/telegram.blade.php',
                ],
            ],
        ],
        [
            'slug' => 'cluster',
            'title' => 'Telegram admin module cluster',
            'route' => 'cluster',
            'items' => [
                [
                    'id' => 'cluster-done',
                    'title' => 'Users notify event cluster title',
                    'trigger' => 'Users notify event cluster trigger',
                    'audience' => 'Users notify event cluster audience',
                    'channels' => ['telegram'],
                    'tariff' => 'Users notify tariff all tg',
                    'cron' => null,
                    'example_telegram' => 'Users notify event cluster tg example',
                    'code_ref' => 'Cluster::sendNotification',
                ],
            ],
        ],
        [
            'slug' => 'monitoring-limits',
            'title' => 'Telegram admin module monitoring limits',
            'route' => 'monitoring.projects.get',
            'items' => [
                [
                    'id' => 'monitoring-limit-exhausted',
                    'title' => 'Users notify event limits title',
                    'trigger' => 'Users notify event limits trigger',
                    'audience' => 'Users notify event limits audience',
                    'channels' => ['telegram', 'email_event'],
                    'tariff' => 'Users notify event limits tariff',
                    'cron' => null,
                    'example_telegram' => 'Users notify event limits tg example',
                    'example_email' => 'Users notify event limits email example',
                    'code_ref' => 'Monitoring\\Limits::notify',
                ],
            ],
        ],
        [
            'slug' => 'monitoring-positions',
            'title' => 'Users notify module monitoring positions',
            'route' => 'monitoring.projects.get',
            'items' => [
                [
                    'id' => 'monitoring-positions-note',
                    'title' => 'Users notify event mon pos title',
                    'trigger' => 'Users notify event mon pos trigger',
                    'audience' => 'Users notify event mon pos audience',
                    'channels' => ['modal'],
                    'tariff' => 'Users notify tariff free only',
                    'cron' => null,
                    'example_modal' => 'Users notify event mon pos example',
                    'code_ref' => 'schedule-paid-prompt (см. модалки)',
                ],
            ],
        ],
        [
            'slug' => 'news',
            'title' => 'Users notify module news',
            'route' => 'news',
            'items' => [
                [
                    'id' => 'news-badge',
                    'title' => 'Users notify event news title',
                    'trigger' => 'Users notify event news trigger',
                    'audience' => 'Users notify event news audience',
                    'channels' => [],
                    'tariff' => 'Users notify tariff all',
                    'cron' => null,
                    'example_modal' => 'Users notify event news example',
                    'code_ref' => 'news_notification (меню)',
                ],
            ],
        ],
        [
            'slug' => 'site-audit',
            'title' => 'Аудит сайта',
            'route' => 'pages.site-audit',
            'items' => [
                [
                    'id' => 'site-audit-crawl-done',
                    'title' => 'Аудит сайта завершён',
                    'trigger' => 'После успешного завершения краула аудита',
                    'audience' => 'Владелец проекта аудита',
                    'channels' => ['email_event'],
                    'tariff' => 'Все тарифы',
                    'cron' => null,
                    'example_email' => 'Письмо со ссылкой на сводку краула и корзинами ошибок',
                    'code_ref' => 'SiteAuditCrawlCompletedNotification',
                ],
            ],
        ],
        [
            'slug' => 'auth',
            'title' => 'Users notify module auth',
            'route' => 'login',
            'items' => [
                [
                    'id' => 'auth-verify-email',
                    'title' => 'Users notify event auth verify title',
                    'trigger' => 'Users notify event auth verify trigger',
                    'audience' => 'Users notify event auth verify audience',
                    'channels' => ['email_service'],
                    'tariff' => 'Users notify tariff all',
                    'cron' => null,
                    'example_email' => 'Users notify event auth verify example',
                    'code_ref' => 'Laravel MustVerifyEmail',
                ],
            ],
        ],
    ],
];
