<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Site Audit — реестр finding codes (фаза A must-have + заготовки)
    | severity: critical|other|warning|info
    | phase: A|B|C|D
    |--------------------------------------------------------------------------
    */
    'queue' => env('SITE_AUDIT_QUEUE', 'site_audit'),
    'user_agent' => env('SITE_AUDIT_UA', 'TitloSiteAuditBot/1.0 (+https://titlo.ru)'),
    'request_timeout' => (int) env('SITE_AUDIT_TIMEOUT', 15),
    'max_redirects' => (int) env('SITE_AUDIT_MAX_REDIRECTS', 10),
    'per_host_rps' => (float) env('SITE_AUDIT_HOST_RPS', 1),
    'large_page_bytes' => (int) env('SITE_AUDIT_LARGE_PAGE_BYTES', 1_500_000),
    'html_path' => env('SITE_AUDIT_HTML_PATH', storage_path('app/site-audit-html')),
    'max_active_crawls_per_user' => 1,
    // local/тесты: не резать по тарифу, пока UI/модуль сырые
    'bypass_limits' => (bool) env('SITE_AUDIT_BYPASS_LIMITS', false),
    'thin_words' => (int) env('SITE_AUDIT_THIN_WORDS', 150),
    'title_min' => (int) env('SITE_AUDIT_TITLE_MIN', 30),
    'title_max' => (int) env('SITE_AUDIT_TITLE_MAX', 70),
    'description_min' => (int) env('SITE_AUDIT_DESC_MIN', 70),
    'description_max' => (int) env('SITE_AUDIT_DESC_MAX', 160),
    // сколько детальных краулов хранить на проект (старше — prune)
    'history_keep_per_project' => (int) env('SITE_AUDIT_HISTORY_KEEP', 200),
    'robots_max_bytes' => (int) env('SITE_AUDIT_ROBOTS_MAX_BYTES', 512000),
    'simhash_hamming_max' => (int) env('SITE_AUDIT_SIMHASH_HAMMING', 6),
    'simhash_max_pairs' => (int) env('SITE_AUDIT_SIMHASH_MAX_PAIRS', 200),
    'share_ttl_days' => (int) env('SITE_AUDIT_SHARE_TTL_DAYS', 0), // 0 = бессрочно
    'broken_link_head_max' => (int) env('SITE_AUDIT_BROKEN_HEAD_MAX', 40),
    'broken_image_head_max' => (int) env('SITE_AUDIT_BROKEN_IMAGE_HEAD_MAX', 50),
    'heavy_image_bytes' => (int) env('SITE_AUDIT_HEAVY_IMAGE_BYTES', 500000),
    'html_critical_min' => (int) env('SITE_AUDIT_HTML_CRITICAL_MIN', 1),
    'lost_file_head_max' => (int) env('SITE_AUDIT_LOST_FILE_HEAD_MAX', 40),
    'lost_file_max_findings' => (int) env('SITE_AUDIT_LOST_FILE_MAX', 80),
    'error_spike_min_count' => (int) env('SITE_AUDIT_ERROR_SPIKE_MIN', 5),
    'error_spike_status_share' => (float) env('SITE_AUDIT_ERROR_SPIKE_STATUS_SHARE', 0.4),
    'error_spike_path_min' => (int) env('SITE_AUDIT_ERROR_SPIKE_PATH_MIN', 5),
    'error_spike_path_rate' => (float) env('SITE_AUDIT_ERROR_SPIKE_PATH_RATE', 0.5),
    'error_spike_delta_min' => (int) env('SITE_AUDIT_ERROR_SPIKE_DELTA_MIN', 5),
    'error_spike_delta_ratio' => (float) env('SITE_AUDIT_ERROR_SPIKE_DELTA_RATIO', 2.0),
    'click_depth_warn' => (int) env('SITE_AUDIT_CLICK_DEPTH_WARN', 4),
    'strong_max' => (int) env('SITE_AUDIT_STRONG_MAX', 20),
    'nausea_classic_max' => (float) env('SITE_AUDIT_NAUSEA_CLASSIC_MAX', 8.0),
    'nausea_academic_max' => (float) env('SITE_AUDIT_NAUSEA_ACADEMIC_MAX', 10.0),
    'bigram_spam_min' => (int) env('SITE_AUDIT_BIGRAM_SPAM_MIN', 4),
    'bigram_spam_density_min' => (float) env('SITE_AUDIT_BIGRAM_SPAM_DENSITY', 1.5),
    'trigram_spam_min' => (int) env('SITE_AUDIT_TRIGRAM_SPAM_MIN', 3),
    'trigram_spam_density_min' => (float) env('SITE_AUDIT_TRIGRAM_SPAM_DENSITY', 1.0),
    'noindex_text_min' => (int) env('SITE_AUDIT_NOINDEX_TEXT_MIN', 40),
    'sitemap_url_cap' => (int) env('SITE_AUDIT_SITEMAP_URL_CAP', 20000),
    'sitemap_not_crawled_sample' => (int) env('SITE_AUDIT_SITEMAP_NOT_CRAWLED_SAMPLE', 80),
    'not_in_sitemap_max' => (int) env('SITE_AUDIT_NOT_IN_SITEMAP_MAX', 500),
    'landing_findings_max' => (int) env('SITE_AUDIT_LANDING_FINDINGS_MAX', 300),
    // Доступность: доля unreachable+5xx среди страниц краула
    'availability_fail_rate' => (float) env('SITE_AUDIT_AVAILABILITY_FAIL_RATE', 0.10),
    // Индекс ПС vs pages_total (XML site: found). Local: выкл., prod: SITE_AUDIT_SERP_INDEX=1
    'serp_index_enabled' => (bool) env('SITE_AUDIT_SERP_INDEX', false),
    'serp_index_engines' => ['yandex', 'google'],
    'serp_index_ratio_low' => (float) env('SITE_AUDIT_SERP_INDEX_RATIO_LOW', 0.5),
    'serp_index_ratio_high' => (float) env('SITE_AUDIT_SERP_INDEX_RATIO_HIGH', 3.0),

    // Сниппеты ПС для посадочных/сэмпла (XML, дорого). Local: выкл., prod: SITE_AUDIT_SERP_SNIPPETS=1
    'serp_snippets_enabled' => (bool) env('SITE_AUDIT_SERP_SNIPPETS', false),
    'serp_snippets_engines' => ['yandex', 'google'],
    'serp_snippets_max_urls' => (int) env('SITE_AUDIT_SERP_SNIPPETS_MAX', 12),

    // PSI (PageSpeed Insights v5). Дорого по времени — выкл. по умолчанию.
    'psi_enabled' => (bool) env('SITE_AUDIT_PSI', false),
    'psi_api_key' => env('SITE_AUDIT_PSI_API_KEY', ''),
    'psi_max_urls' => (int) env('SITE_AUDIT_PSI_MAX_URLS', 3),
    'psi_strategies' => ['mobile', 'desktop'],
    'psi_score_warn' => (float) env('SITE_AUDIT_PSI_SCORE_WARN', 0.5),
    'psi_timeout' => (int) env('SITE_AUDIT_PSI_TIMEOUT', 90),

    // Content risk lite (keyword classifiers + word repeats). Cheap — on by default.
    'content_risk_enabled' => (bool) env('SITE_AUDIT_CONTENT_RISK', true),
    'content_risk_adult_min_hits' => (int) env('SITE_AUDIT_ADULT_MIN_HITS', 2),
    'content_risk_negative_min_hits' => (int) env('SITE_AUDIT_NEGATIVE_MIN_HITS', 2),
    'word_repeat_min_len' => (int) env('SITE_AUDIT_WORD_REPEAT_MIN_LEN', 4),
    'word_repeat_min_count' => (int) env('SITE_AUDIT_WORD_REPEAT_MIN_COUNT', 3),
    'content_risk_adult' => [
        'порно', 'порнуха', 'xxx', 'erotica', 'эротика', 'сексшоп', 'секс-шоп',
        'эскорт', 'webcam', 'camsoda', 'onlyfans', 'hentai', 'nsfw',
        'интим-услуги', 'интим услуги', 'prostitut', 'проститут',
    ],
    'content_risk_negative' => [
        'суицид', 'самоубийств', 'наркотик', 'героин', 'кокаин', 'амфетамин',
        'спайс', 'мефедрон', 'взрывчатк', 'терроризм', 'террорист',
        'убийство', 'расчленен', 'педофил', 'насилие над',
    ],
    'landing_plagiarism_max' => (int) env('SITE_AUDIT_LANDING_PLAGIARISM_MAX', 200),
    'cannibalization_max' => (int) env('SITE_AUDIT_CANNIBALIZATION_MAX', 200),
    'cannibalization_min_token' => (int) env('SITE_AUDIT_CANNIBAL_MIN_TOKEN', 4),
    'cannibalization_min_hits' => (int) env('SITE_AUDIT_CANNIBAL_MIN_HITS', 2),
    'ad_cannibalization_max' => (int) env('SITE_AUDIT_AD_CANNIBAL_MAX', 200),
    'ad_cannibalization_thin_words' => (int) env('SITE_AUDIT_AD_CANNIBAL_THIN', 150),
    'landing_query_match_max' => (int) env('SITE_AUDIT_LANDING_QUERY_MAX', 300),
    'landing_query_min_hits' => (int) env('SITE_AUDIT_LANDING_QUERY_MIN_HITS', 2),
    'landing_query_min_share' => (float) env('SITE_AUDIT_LANDING_QUERY_MIN_SHARE', 0.5),
    'action_plan_max_items' => (int) env('SITE_AUDIT_ACTION_PLAN_MAX', 25),
    'action_plan_ai_enabled' => (bool) env('SITE_AUDIT_ACTION_PLAN_AI', true),

    // Хосты/пути партнёрских сетей (probable_affiliate)
    'affiliate_networks' => [
        'admitad' => ['admitad.com', 'ad.admitad', 'admitad'],
        'actionpay' => ['actionpay.ru', 'actionpay'],
        'gdeslon' => ['gdeslon.ru', 'gdeslon'],
        'cityads' => ['cityads.com', 'cityads'],
        'advertise' => ['advertise.ru'],
        'tradetracker' => ['tradetracker.com'],
        'awin' => ['awin.com', 'awin1.com'],
        'cj' => ['cj.com', 'dpbolvw.net', 'anrdoezrs.net'],
        'amazon' => ['amazon.com/gp/product', 'amzn.to', 'amazon.ru'],
        'generic' => ['/affiliate', 'partner_id=', 'aff_id=', 'click.php', 'go.php?'],
    ],

    'no_outbound_internal_max' => (int) env('SITE_AUDIT_NO_OUTBOUND_MAX', 500),
    'risky_query_max' => (int) env('SITE_AUDIT_RISKY_QUERY_MAX', 300),
    'pagination_param_max' => (int) env('SITE_AUDIT_PAGINATION_PARAM_MAX', 300),
    'risky_query_key_count' => (int) env('SITE_AUDIT_RISKY_QUERY_KEYS', 8),
    'risky_query_len' => (int) env('SITE_AUDIT_RISKY_QUERY_LEN', 120),
    'risky_query_keys' => [
        'phpsessid', 'sid', 'sessionid', 'session_id', 'jsessionid',
        'sort', 'order', 'orderby', 'sortby',
    ],
    'pagination_query_keys' => [
        'page', 'p', 'pagen_1', 'paged', 'offset', 'start',
    ],
    'facet_query_keys' => [
        'filter', 'filters', 'facet', 'facets',
    ],
    'soft_404_title_patterns' => [
        '404',
        'not found',
        'page not found',
        'страница не найдена',
        'не найдена',
        'ошибка 404',
    ],

    /*
    | Коды, попадающие в SEO-сводку (остальные — tech).
    */
    'seo_codes' => [
        'duplicate_title',
        'duplicate_description',
        'duplicate_content',
        'similar_pages',
        'empty_title',
        'empty_description',
        'multiple_title_or_description',
        'noindex',
        'indexing_blocked',
        'canonical_foreign',
        'canonical_empty',
        'canonical_not_self',
        'multiple_canonical',
        'pages_with_canonical',
        'missing_h1',
        'multiple_h1',
        'thin_content',
        'title_too_short',
        'title_too_long',
        'description_too_short',
        'description_too_long',
        'title_equals_h1',
        'title_equals_description',
        'description_equals_h1',
        'h1_equals_h2',
        'heading_hierarchy',
        'too_many_strong',
        'duplicate_links',
        'external_links',
        'meta_spam',
        'h1_spam',
        'text_nausea',
        'text_bigram_spam',
        'text_trigram_spam',
        'no_unique_images',
        'text_in_noindex',
        'landing_not_in_sitemap',
        'landing_not_crawled',
        'landing_url_changed',
        'landing_plagiarism_suspect',
        'landing_no_inbound_internal',
        'keyword_cannibalization',
        'ad_cannibalization',
        'landing_query_mismatch',
        'commercial_missing_contacts',
        'commercial_missing_price',
        'commercial_missing_cta',
        'commercial_missing_delivery',
        'commercial_missing_payment',
        'commercial_missing_stock',
        'commercial_missing_reviews',
        'adult_content',
        'negative_content',
        'word_repeat_in_sentence',
        'robots_txt_closed',
        'robots_blocked',
        'meta_nofollow',
        'soft_404',
        'orphan_pages',
        'duplicate_url_variants',
        'www_both_available',
        'http_https_both_available',
        'page_has_broken_links',
        'broken_internal_link',
        'deep_pages',
        'site_availability',
        'index_count_mismatch',
        'serp_snippets',
        'serp_title_mismatch',
        'serp_not_indexed',
        'serp_snippet_source',
        'probable_affiliate',
        'seo_meta_errors',
        'multiple_canonical',
        'no_outbound_internal',
        'risky_query_params',
        'pagination_param',
    ],

    /*
    | Пресеты скорости (запросов в секунду на хост).
    | slow ≈ осторожно против антибота, turbo — только свои/тестовые сайты.
    */
    'speed_presets' => [
        'slow' => 1.0,
        'normal' => 5.0,
        'fast' => 10.0,
        'turbo' => 15.0,
    ],

    /*
    | Пул UA под ротацию (реальные браузеры). Не светим TitloBot по умолчанию.
    */
    'user_agents' => [
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36',
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36',
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0',
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0',
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0',
        'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0',
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15',
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15',
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0',
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0',
        'Mozilla/5.0 (iPhone; CPU iPhone OS 17_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2 Mobile/15E148 Safari/604.1',
        'Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1',
        'Mozilla/5.0 (Linux; Android 14; Pixel 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Mobile Safari/537.36',
        'Mozilla/5.0 (Linux; Android 13; SM-S918B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Mobile Safari/537.36',
        'Mozilla/5.0 (Linux; Android 12; Pixel 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36',
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
    ],

    'findings' => [
        // —— Фаза A (MVP) ——
        'http_4xx' => [
            'phase' => 'A',
            'severity' => 'critical',
            'title' => 'Ошибки 4xx',
            'description' => 'Страница отвечает клиентской ошибкой (404, 403 и т.п.).',
        ],
        'http_5xx' => [
            'phase' => 'A',
            'severity' => 'critical',
            'title' => 'Ошибки 5xx',
            'description' => 'Страница отвечает серверной ошибкой (500, 502, 503…).',
        ],
        'unreachable' => [
            'phase' => 'A',
            'severity' => 'critical',
            'title' => 'Недоступные страницы',
            'description' => 'Не удалось получить ответ (timeout, DNS, connection error).',
        ],
        'redirect' => [
            'phase' => 'A',
            'severity' => 'warning',
            'title' => 'Редиректы',
            'description' => 'URL отвечает редиректом на другой адрес.',
        ],
        'redirect_chain_long' => [
            'phase' => 'A',
            'severity' => 'other',
            'title' => 'Множественные редиректы',
            'description' => 'Слишком длинная цепочка редиректов.',
        ],
        'duplicate_title' => [
            'phase' => 'A',
            'severity' => 'critical',
            'title' => 'Дубли TITLE',
            'description' => 'Несколько страниц с одинаковым TITLE.',
        ],
        'duplicate_description' => [
            'phase' => 'A',
            'severity' => 'critical',
            'title' => 'Дубли Description',
            'description' => 'Несколько страниц с одинаковым Description.',
        ],
        'duplicate_content' => [
            'phase' => 'B',
            'severity' => 'critical',
            'title' => 'Дубли контента',
            'description' => 'Несколько страниц с одинаковым текстовым content_hash.',
        ],
        'similar_pages' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Похожие страницы',
            'description' => 'Страницы со схожим текстом (SimHash, порог Hamming).',
        ],
        'empty_title' => [
            'phase' => 'A',
            'severity' => 'critical',
            'title' => 'Пустой TITLE',
            'description' => 'На странице отсутствует или пуст тег title.',
        ],
        'empty_description' => [
            'phase' => 'A',
            'severity' => 'warning',
            'title' => 'Пустой Description',
            'description' => 'Отсутствует meta description.',
        ],
        'multiple_title_or_description' => [
            'phase' => 'A',
            'severity' => 'critical',
            'title' => 'Несколько title/description',
            'description' => 'В HTML больше одного title или meta description.',
        ],
        'noindex' => [
            'phase' => 'A',
            'severity' => 'warning',
            'title' => 'Страницы с noindex',
            'description' => 'Страница закрыта от индексации meta robots или X-Robots-Tag.',
        ],
        'canonical_foreign' => [
            'phase' => 'A',
            'severity' => 'other',
            'title' => 'Canonical на чужой домен',
            'description' => 'rel=canonical указывает на другой хост.',
        ],
        'canonical_not_self' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Canonical не на себя',
            'description' => 'rel=canonical указывает на другой URL того же сайта (не self-canonical).',
        ],
        'canonical_empty' => [
            'phase' => 'A',
            'severity' => 'info',
            'title' => 'Страницы без canonical',
            'description' => 'Не задан rel=canonical (инфо).',
        ],
        'multiple_canonical' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Несколько rel=canonical',
            'description' => 'В HTML больше одного link rel=canonical.',
        ],
        'seo_meta_errors' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'SEO-ошибки META тегов',
            'description' => 'Сводный отчёт по ошибкам title/description/canonical и связанным META-сигналам (стык с модулем мета-тегов без повторного HTTP).',
            'virtual' => true,
            'codes' => [
                'empty_title',
                'empty_description',
                'multiple_title_or_description',
                'multiple_canonical',
                'canonical_not_self',
                'title_too_short',
                'title_too_long',
                'description_too_short',
                'description_too_long',
                'title_equals_h1',
                'title_equals_description',
                'description_equals_h1',
                'meta_spam',
            ],
        ],
        'page_too_large' => [
            'phase' => 'A',
            'severity' => 'warning',
            'title' => 'Очень большие страницы',
            'description' => 'Размер ответа превышает порог.',
        ],
        'missing_h1' => [
            'phase' => 'A',
            'severity' => 'warning',
            'title' => 'Страницы без H1',
            'description' => 'На странице нет заголовка H1.',
        ],
        'multiple_h1' => [
            'phase' => 'A',
            'severity' => 'critical',
            'title' => 'Несколько H1',
            'description' => 'На странице больше одного H1.',
        ],
        'thin_content' => [
            'phase' => 'A',
            'severity' => 'warning',
            'title' => 'Тощие страницы',
            'description' => 'Мало текстового контента (ниже порога по числу слов).',
        ],
        'title_too_short' => [
            'phase' => 'A',
            'severity' => 'warning',
            'title' => 'Короткий TITLE',
            'description' => 'TITLE короче рекомендуемой длины.',
        ],
        'title_too_long' => [
            'phase' => 'A',
            'severity' => 'warning',
            'title' => 'Длинный TITLE',
            'description' => 'TITLE длиннее рекомендуемой длины.',
        ],
        'description_too_short' => [
            'phase' => 'A',
            'severity' => 'warning',
            'title' => 'Короткий Description',
            'description' => 'Description короче рекомендуемой длины.',
        ],
        'description_too_long' => [
            'phase' => 'A',
            'severity' => 'warning',
            'title' => 'Длинный Description',
            'description' => 'Description длиннее рекомендуемой длины.',
        ],
        'title_equals_h1' => [
            'phase' => 'A',
            'severity' => 'warning',
            'title' => 'TITLE = H1',
            'description' => 'TITLE совпадает с H1.',
        ],
        'title_equals_description' => [
            'phase' => 'A',
            'severity' => 'warning',
            'title' => 'TITLE = Description',
            'description' => 'TITLE совпадает с Description.',
        ],
        'description_equals_h1' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'DESCRIPTION = H1',
            'description' => 'Meta description совпадает с H1.',
        ],
        'h1_equals_h2' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'H1 = H2',
            'description' => 'Текст H1 совпадает с одним из H2.',
        ],
        'heading_hierarchy' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Нарушена иерархия заголовков',
            'description' => 'Заголовок до первого H1 или пропуск уровня (например H1→H3) в outline h1–h6.',
            'group' => 'seo',
        ],
        'too_many_strong' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Много strong/b',
            'description' => 'На странице слишком много тегов strong/b (риск переспама выделениями).',
        ],
        'duplicate_links' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Дубли одной ссылки',
            'description' => 'Один и тот же внутренний URL встречается в ссылках страницы несколько раз.',
        ],
        'external_links' => [
            'phase' => 'B',
            'severity' => 'info',
            'title' => 'Исходящие на другие сайты',
            'description' => 'На странице есть ссылки на внешние домены.',
        ],
        'meta_spam' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Переспам в META',
            'description' => 'В TITLE или Description одно значимое слово повторяется слишком часто.',
        ],
        'h1_spam' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Переспам в H1',
            'description' => 'В H1 одно значимое слово повторяется слишком часто.',
        ],
        'text_nausea' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Тошнота текста',
            'description' => 'Классическая или академическая тошнота текста выше порога.',
        ],
        'text_bigram_spam' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Переспам биграммами',
            'description' => 'Одна и та же биграмма слишком часто встречается в тексте страницы.',
        ],
        'text_trigram_spam' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Переспам триграммами',
            'description' => 'Одна и та же триграмма слишком часто встречается в тексте страницы.',
            'group' => 'seo',
        ],
        'no_unique_images' => [
            'phase' => 'B',
            'severity' => 'info',
            'title' => 'Нет уникальных изображений',
            'description' => 'На странице нет изображений с уникальным src.',
        ],
        'text_in_noindex' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Текст в noindex',
            'description' => 'Внутри тегов/комментариев noindex есть заметный объём текста.',
        ],
        'images_without_alt' => [
            'phase' => 'A',
            'severity' => 'warning',
            'title' => 'Изображения без alt',
            'description' => 'На странице есть img без атрибута alt или с пустым alt.',
        ],

        // —— Фаза B (lite) ——
        'robots_txt_error' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Ошибки robots.txt',
            'description' => 'Проблемы с файлом robots.txt: недоступен, пустой, слишком большой, битые Sitemap: и т.п.',
        ],
        'robots_txt_closed' => [
            'phase' => 'B',
            'severity' => 'critical',
            'title' => 'Закрытие robots.txt',
            'description' => 'В robots.txt для User-agent: * задано Disallow: / — сайт закрыт от обхода роботов.',
        ],
        'robots_blocked' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'URL закрыт в robots.txt',
            'description' => 'Страница попадает под Disallow в robots.txt.',
        ],
        'indexing_blocked' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Блокировки индексации',
            'description' => 'Сводный отчёт: noindex, закрытие в robots.txt и ошибки robots.txt.',
            'virtual' => true,
            'codes' => ['noindex', 'robots_blocked', 'robots_txt_closed', 'robots_txt_error'],
        ],
        'pages_with_canonical' => [
            'phase' => 'A',
            'severity' => 'info',
            'title' => 'Страницы с rel=canonical',
            'description' => 'Список страниц, у которых задан rel=canonical (и его target).',
            'source' => 'pages_canonical',
        ],
        'pages_with_iframe' => [
            'phase' => 'B',
            'severity' => 'info',
            'title' => 'Страницы с frame/iframe',
            'description' => 'На странице есть frame или iframe.',
        ],
        'mixed_content' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Смешанный контент',
            'description' => 'На HTTPS-странице есть ресурсы по http://.',
        ],
        'insecure_form' => [
            'phase' => 'B',
            'severity' => 'critical',
            'title' => 'Форма на http с HTTPS-страницы',
            'description' => 'На HTTPS-странице есть form action=http:// — данные уходят без шифрования.',
            'group' => 'tech',
        ],
        'bad_doctype' => [
            'phase' => 'B',
            'severity' => 'info',
            'title' => 'Неверный HTML DOCTYPE',
            'description' => 'DOCTYPE отсутствует или выглядит необычно (не HTML5).',
        ],
        'meta_nofollow' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Nofollow (meta)',
            'description' => 'Страница закрыта nofollow в meta robots / X-Robots-Tag.',
        ],
        'links_nofollow' => [
            'phase' => 'B',
            'severity' => 'info',
            'title' => 'Ссылки с nofollow',
            'description' => 'На странице есть исходящие ссылки с rel=nofollow.',
        ],
        'external_assets' => [
            'phase' => 'B',
            'severity' => 'info',
            'title' => 'Файлы с внешних сайтов',
            'description' => 'На странице подключены script/link/img с чужого хоста.',
        ],
        'soft_404' => [
            'phase' => 'B',
            'severity' => 'other',
            'title' => 'Soft 404',
            'description' => 'Ответ 200, но страница похожа на «не найдено» (паттерн в title/H1 или крайне мало текста).',
        ],
        'orphan_pages' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Страницы-сироты',
            'description' => 'В рамках краула нет входящих внутренних ссылок на эту страницу (кроме главной).',
        ],
        'sitemap_missing' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Sitemap не найден',
            'description' => 'Не удалось получить URL из sitemap.xml / sitemap index / Sitemap: в robots.txt.',
        ],
        'sitemap_error' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Ошибка sitemap',
            'description' => 'Конкретный sitemap недоступен, пустой или не похож на XML.',
        ],
        'not_in_sitemap' => [
            'phase' => 'B',
            'severity' => 'info',
            'title' => 'Страница не в sitemap',
            'description' => 'URL обойден краулом, но отсутствует в sitemap сайта.',
        ],
        'sitemap_not_crawled' => [
            'phase' => 'B',
            'severity' => 'info',
            'title' => 'В sitemap, не в крауле',
            'description' => 'URL есть в sitemap, но не попал в текущий краул (лимит / не дошли по ссылкам).',
        ],
        'landing_not_in_sitemap' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Посадочная не в sitemap',
            'description' => 'Целевой URL из мониторинга позиций отсутствует в sitemap сайта.',
        ],
        'landing_not_crawled' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Посадочная не в крауле',
            'description' => 'Целевой URL из мониторинга не попал в обход (лимит или нет во внутренних ссылках/sitemap-сиде).',
        ],
        'landing_url_changed' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Изменения URL посадочных',
            'description' => 'Целевой URL (monitoring.page) для запроса изменился относительно предыдущего краула проекта.',
        ],
        'duplicate_url_variants' => [
            'phase' => 'A',
            'severity' => 'other',
            'title' => 'Дубли URL (www/http/slash)',
            'description' => 'Одна и та же страница доступна под разными вариантами URL (схема, www, слэш).',
        ],
        'www_both_available' => [
            'phase' => 'A',
            'severity' => 'critical',
            'title' => 'Сайт открыт и с www, и без www',
            'description' => 'Оба зеркала (www и без www) отдают контент и не сводятся редиректом на один хост. Это дубли всего сайта — грубое нарушение (склейка, вес, индексация). Нужен 301 на один канонический хост.',
        ],
        'http_https_both_available' => [
            'phase' => 'A',
            'severity' => 'critical',
            'title' => 'Сайт открыт и по http, и по https',
            'description' => 'HTTP отвечает без редиректа на HTTPS, при этом HTTPS тоже доступен. Дубли по схеме — грубое нарушение. Нужен 301 http→https.',
        ],
        'page_has_broken_links' => [
            'phase' => 'A',
            'severity' => 'warning',
            'title' => 'Страницы с битыми ссылками',
            'description' => 'На странице есть внутренние ссылки на недоступные/ошибочные URL.',
        ],
        'broken_internal_link' => [
            'phase' => 'A',
            'severity' => 'critical',
            'title' => 'Битые внутренние ссылки',
            'description' => 'Целевой URL отвечает 4xx/5xx или недоступен (по данным краула или HEAD-проверке).',
        ],
        'page_has_bad_links' => [
            'phase' => 'C',
            'severity' => 'warning',
            'title' => 'Плохие ссылки',
            'description' => 'Ссылки с пустым href, #, javascript: или неразрешимым URL (не HTTP-битые).',
            'group' => 'tech',
        ],
        'html_critical_errors' => [
            'phase' => 'C',
            'severity' => 'other',
            'title' => 'Критические ошибки HTML',
            'description' => 'Сэмпл критичных ошибок разметки (libxml ERROR/FATAL + эвристики). Не полный W3C-validator.',
            'group' => 'tech',
        ],
        'lost_file' => [
            'phase' => 'C',
            'severity' => 'warning',
            'title' => 'Потерянные файлы',
            'description' => 'CSS/JS ресурс недоступен (HEAD), с указанием страниц-referrer.',
            'group' => 'tech',
        ],
        'adult_content' => [
            'phase' => 'C',
            'severity' => 'warning',
            'title' => '«Взрослый» контент',
            'description' => 'В тексте страницы найдены маркеры adult-тематики (keyword lite, не ML).',
            'group' => 'seo',
        ],
        'negative_content' => [
            'phase' => 'C',
            'severity' => 'warning',
            'title' => 'Негативный контент',
            'description' => 'В тексте страницы найдены маркеры негативной тематики (keyword lite, не ML).',
            'group' => 'seo',
        ],
        'word_repeat_in_sentence' => [
            'phase' => 'C',
            'severity' => 'info',
            'title' => 'Повторы слова в предложении',
            'description' => 'Одно и то же слово повторяется в предложении выше порога (стилистика / переспам).',
            'group' => 'seo',
        ],
        'landing_plagiarism_suspect' => [
            'phase' => 'C',
            'severity' => 'warning',
            'title' => 'Поиск плагиата на посадочных (lite)',
            'description' => 'Посадочная совпадает или очень похожа на другую страницу сайта (внутренний дубль/simhash). Внешний антиплагиат — позже.',
            'group' => 'seo',
        ],
        'landing_no_inbound_internal' => [
            'phase' => 'C',
            'severity' => 'warning',
            'title' => 'Нет внутренних ссылок на посадочную',
            'description' => 'На посадочную из мониторинга нет входящих внутренних ссылок в крауле (кроме самоссылок).',
            'group' => 'seo',
        ],
        'keyword_cannibalization' => [
            'phase' => 'C',
            'severity' => 'warning',
            'title' => 'Каннибализация запросов',
            'description' => 'Запрос из мониторинга встречается в title/h1 у страницы, отличной от назначенной посадочной.',
            'group' => 'seo',
        ],
        'ad_cannibalization' => [
            'phase' => 'C',
            'severity' => 'warning',
            'title' => 'Каннибализация рекламой',
            'description' => 'Запрос из мониторинга в title/h1 у promo/PPC-подобной страницы, отличной от SEO-посадочной (lite без Директа).',
            'group' => 'seo',
        ],
        'landing_query_mismatch' => [
            'phase' => 'D',
            'severity' => 'warning',
            'title' => 'Несоответствие запроса посадочной',
            'description' => 'Запрос из мониторинга слабо отражён в title/h1/description назначенной посадочной (lite по мета).',
            'group' => 'seo',
        ],
        'commercial_missing_contacts' => [
            'phase' => 'C',
            'severity' => 'info',
            'title' => 'Телефон / адрес на коммерческих',
            'description' => 'Коммерческая страница без телефона и/или адреса в видимом тексте (эвристика).',
            'group' => 'seo',
        ],
        'commercial_missing_price' => [
            'phase' => 'D',
            'severity' => 'info',
            'title' => 'Нет цены на коммерческой',
            'description' => 'Коммерческая страница без явной цены (₽/руб/«цена») в тексте.',
            'group' => 'seo',
        ],
        'commercial_missing_cta' => [
            'phase' => 'D',
            'severity' => 'info',
            'title' => 'Нет CTA купить/заказать',
            'description' => 'Коммерческая страница без явного CTA (купить / заказать / в корзину).',
            'group' => 'seo',
        ],
        'commercial_missing_delivery' => [
            'phase' => 'D',
            'severity' => 'info',
            'title' => 'Нет блока доставки',
            'description' => 'Коммерческая страница без упоминания доставки / самовывоза.',
            'group' => 'seo',
        ],
        'commercial_missing_payment' => [
            'phase' => 'D',
            'severity' => 'info',
            'title' => 'Нет способов оплаты',
            'description' => 'Коммерческая страница без упоминания оплаты / карт / рассрочки.',
            'group' => 'seo',
        ],
        'commercial_missing_stock' => [
            'phase' => 'D',
            'severity' => 'info',
            'title' => 'Нет статуса наличия',
            'description' => 'Коммерческая страница без «в наличии» / остатка / под заказ.',
            'group' => 'seo',
        ],
        'commercial_missing_reviews' => [
            'phase' => 'D',
            'severity' => 'info',
            'title' => 'Нет отзывов / рейтинга',
            'description' => 'Коммерческая страница без упоминания отзывов или рейтинга.',
            'group' => 'seo',
        ],
        'commercial_factors' => [
            'phase' => 'D',
            'severity' => 'info',
            'title' => 'Коммерческие факторы (lite)',
            'description' => 'Сводка: контакты, цена, CTA, доставка, оплата, наличие, отзывы на коммерческих страницах. Без сравнения с ТОП конкурентов.',
            'virtual' => true,
            'group' => 'seo',
            'codes' => [
                'commercial_missing_contacts',
                'commercial_missing_price',
                'commercial_missing_cta',
                'commercial_missing_delivery',
                'commercial_missing_payment',
                'commercial_missing_stock',
                'commercial_missing_reviews',
            ],
        ],
        'broken_image' => [
            'phase' => 'C',
            'severity' => 'warning',
            'title' => 'Битые изображения',
            'description' => 'img src недоступен (4xx/5xx/ошибка) по HEAD-сэмплу.',
            'group' => 'tech',
        ],
        'heavy_image' => [
            'phase' => 'C',
            'severity' => 'info',
            'title' => 'Слишком тяжёлые изображения',
            'description' => 'Размер картинки (Content-Length) выше порога.',
            'group' => 'tech',
        ],
        'error_spike' => [
            'phase' => 'C',
            'severity' => 'warning',
            'title' => 'Выбросы ошибок',
            'description' => 'Аномалии: кластер одного HTTP-кода, «горящий» префикс URL или скачок ошибок vs прошлый краул.',
            'group' => 'tech',
        ],
        'psi_mobile' => [
            'phase' => 'C',
            'severity' => 'info',
            'title' => 'Мобильные устройства (PSI)',
            'description' => 'PageSpeed Insights (strategy=mobile): Performance score и Core Web Vitals.',
            'group' => 'tech',
        ],
        'psi_desktop' => [
            'phase' => 'C',
            'severity' => 'info',
            'title' => 'Компьютеры (PSI)',
            'description' => 'PageSpeed Insights (strategy=desktop): Performance score и Core Web Vitals.',
            'group' => 'tech',
        ],
        'deep_pages' => [
            'phase' => 'B',
            'severity' => 'info',
            'title' => 'Глубокие страницы',
            'description' => 'Страница далеко от главной по внутренним ссылкам (много кликов).',
        ],
        'site_availability' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Проблемы доступности сайта',
            'description' => 'Корень недоступен/ошибочен или доля unreachable/4xx/5xx среди страниц краула выше порога.',
        ],
        'index_count_mismatch' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Индекс ПС ≠ страниц сайта',
            'description' => 'Число документов site:host в Яндекс/Google сильно расходится с числом страниц, найденных краулом.',
        ],
        'serp_snippets' => [
            'phase' => 'B',
            'severity' => 'info',
            'title' => 'Сниппеты Яндекс / Google',
            'description' => 'Title и текст сниппета из выдачи ПС для посадочных (и сэмпла страниц краула).',
            'group' => 'seo',
        ],
        'serp_title_mismatch' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'TITLE страницы ≠ TITLE в выдаче',
            'description' => 'Заголовок в HTML заметно отличается от title в сниппете Яндекс/Google.',
            'group' => 'seo',
        ],
        'serp_not_indexed' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'URL не найден в выдаче ПС',
            'description' => 'Посадочная / страница сэмпла не обнаружена в выдаче Яндекс или Google (site:/url).',
            'group' => 'seo',
        ],
        'serp_snippet_source' => [
            'phase' => 'C',
            'severity' => 'info',
            'title' => 'Подсветка источника сниппета',
            'description' => 'Откуда ПС, похоже, взяла title/текст сниппета: title, h1 или description страницы.',
            'group' => 'seo',
        ],
        'probable_affiliate' => [
            'phase' => 'C',
            'severity' => 'info',
            'title' => 'Вероятные аффилиаты',
            'description' => 'На странице есть исходящие ссылки на типичные партнёрские сети / affiliate-паттерны.',
            'group' => 'seo',
        ],
        'no_outbound_internal' => [
            'phase' => 'B',
            'severity' => 'info',
            'title' => 'Страницы без исходящих внутренних',
            'description' => 'У страницы нет исходящих внутренних ссылок в крауле (тупик перелинковки).',
        ],
        'risky_query_params' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Рисковые параметры URL',
            'description' => 'В query есть session/sort или слишком длинный/широкий набор параметров (риск дублей в индексе).',
        ],
        'pagination_param' => [
            'phase' => 'B',
            'severity' => 'info',
            'title' => 'Пагинация / фильтры в URL',
            'description' => 'URL похож на страницу пагинации или facet-фильтра (?page=, /page/N, filter=…).',
        ],
        /*
         * Deep-link в существующий модуль (не finding краула).
         * В дереве SEO → «Анализ конкурентов»; detector/HTML не нужны.
         */
        'site_competitors' => [
            'phase' => 'D',
            'severity' => 'info',
            'title' => 'Конкуренты сайта',
            'description' => 'Сводный анализ конкурентов по запросам — отдельный модуль Titlo (не дублируем краул).',
            'group' => 'seo',
            'external' => true,
            'route' => 'competitor.analysis',
        ],
        'security_headers' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Безопасность (HTTP-заголовки)',
            'description' => 'Сводка: нет HSTS / XFO / XCTO / CSP / Referrer-Policy / Permissions-Policy / COOP / COEP / CORP, insecure forms, mixed content.',
            'virtual' => true,
            'group' => 'tech',
            'codes' => [
                'missing_hsts',
                'missing_x_frame_options',
                'missing_x_content_type_options',
                'missing_csp',
                'missing_referrer_policy',
                'missing_permissions_policy',
                'missing_coop',
                'missing_coep',
                'missing_corp',
                'insecure_form',
                'mixed_content',
            ],
        ],
        'missing_hsts' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Нет Strict-Transport-Security',
            'description' => 'На HTTPS-ответе нет заголовка HSTS.',
            'group' => 'tech',
        ],
        'missing_x_frame_options' => [
            'phase' => 'B',
            'severity' => 'info',
            'title' => 'Нет X-Frame-Options',
            'description' => 'Ответ не задаёт X-Frame-Options (риск clickjacking).',
            'group' => 'tech',
        ],
        'missing_x_content_type_options' => [
            'phase' => 'B',
            'severity' => 'info',
            'title' => 'Нет X-Content-Type-Options',
            'description' => 'Ответ не задаёт X-Content-Type-Options: nosniff.',
            'group' => 'tech',
        ],
        'missing_csp' => [
            'phase' => 'C',
            'severity' => 'info',
            'title' => 'Нет Content-Security-Policy',
            'description' => 'Ответ не задаёт Content-Security-Policy (XSS / injection риск).',
            'group' => 'tech',
        ],
        'missing_referrer_policy' => [
            'phase' => 'C',
            'severity' => 'info',
            'title' => 'Нет Referrer-Policy',
            'description' => 'Ответ не задаёт Referrer-Policy (утечка URL в Referer).',
            'group' => 'tech',
        ],
        'missing_permissions_policy' => [
            'phase' => 'C',
            'severity' => 'info',
            'title' => 'Нет Permissions-Policy',
            'description' => 'Ответ не задаёт Permissions-Policy (или legacy Feature-Policy).',
            'group' => 'tech',
        ],
        'missing_coop' => [
            'phase' => 'C',
            'severity' => 'info',
            'title' => 'Нет Cross-Origin-Opener-Policy',
            'description' => 'Ответ не задаёт COOP (изоляция browsing context / Spectre-класс атак).',
            'group' => 'tech',
        ],
        'missing_coep' => [
            'phase' => 'C',
            'severity' => 'info',
            'title' => 'Нет Cross-Origin-Embedder-Policy',
            'description' => 'Ответ не задаёт COEP (нужен вместе с COOP для crossOriginIsolated).',
            'group' => 'tech',
        ],
        'missing_corp' => [
            'phase' => 'C',
            'severity' => 'info',
            'title' => 'Нет Cross-Origin-Resource-Policy',
            'description' => 'Ответ не задаёт CORP (защита ресурса от чужого embedding).',
            'group' => 'tech',
        ],
        'missing_charset' => [
            'phase' => 'B',
            'severity' => 'info',
            'title' => 'Нет charset в HTML',
            'description' => 'В документе не найден meta charset / Content-Type charset.',
            'group' => 'tech',
        ],
    ],
];
