<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Site Audit — реестр finding codes (фаза A must-have + заготовки)
    | severity: critical|other|important|warning|info
    |   important = «Важные замечания» (similar_pages, sitemap_missing, broken_external_link), warning = обычные «Замечания»/Предупреждения
    | phase: A|B|C|D
    |--------------------------------------------------------------------------
    */
    // local + remote MySQL: не класть jobs в общий site_audit — prod съест тик без локального crawl_N.json.
    'queue' => env('SITE_AUDIT_QUEUE') ?: (env('APP_ENV') === 'local' ? 'site_audit_local' : 'site_audit'),
    // Тяжёлая агрегация отдельно — иначе Aggregate* занимает воркеры и тормозит fetch.
    'aggregate_queue' => env('SITE_AUDIT_AGGREGATE_QUEUE')
        ?: (env('APP_ENV') === 'local' ? 'site_audit_aggregate_local' : 'site_audit_aggregate'),

    'user_agent' => env('SITE_AUDIT_UA', 'TitloSiteAuditBot/1.0 (+https://titlo.ru)'),
    // Повтор внешней проверки без слова Bot в UA — иначе WAF рвёт TLS (пример: almamed.su).
    'link_check_browser_ua' => env(
        'SITE_AUDIT_LINK_CHECK_BROWSER_UA',
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
    ),
    'link_check_timeout' => (float) env('SITE_AUDIT_LINK_CHECK_TIMEOUT', 12),
    'link_check_connect_timeout' => (float) env('SITE_AUDIT_LINK_CHECK_CONNECT_TIMEOUT', 6),
    'request_timeout' => (int) env('SITE_AUDIT_TIMEOUT', 15),
    'max_redirects' => (int) env('SITE_AUDIT_MAX_REDIRECTS', 10),
    'per_host_rps' => (float) env('SITE_AUDIT_HOST_RPS', 1),
    'large_page_bytes' => (int) env('SITE_AUDIT_LARGE_PAGE_BYTES', 1_500_000),
    'html_path' => env('SITE_AUDIT_HTML_PATH', storage_path('app/site-audit-html')),
    // Body на диск на время parse (не HTML.gz). Чистится сразу + prune TTL/caps.
    'body_tempfile_enabled' => (bool) env('SITE_AUDIT_BODY_TEMPFILE', true),
    'body_temp_path' => env('SITE_AUDIT_BODY_TEMP_PATH', storage_path('app/site-audit-body-tmp')),
    'body_temp_max_age_sec' => (int) env('SITE_AUDIT_BODY_TEMP_MAX_AGE', 1800), // 30 мин
    'body_temp_max_total_bytes' => (int) env('SITE_AUDIT_BODY_TEMP_MAX_BYTES', 200_000_000), // 200 MB
    'body_temp_max_files' => (int) env('SITE_AUDIT_BODY_TEMP_MAX_FILES', 200),
    // Сколько своих проверок пользователь может гонять параллельно (остальные — queued_wait).
    'max_active_crawls_per_user' => (int) env('SITE_AUDIT_MAX_ACTIVE_PER_USER', 2),
    // Глобально на сервер: ≈ numprocs site_audit. На proxy2 — SITE_AUDIT_GLOBAL_MAX_ACTIVE.
    'global_max_active_crawls' => (int) env('SITE_AUDIT_GLOBAL_MAX_ACTIVE', 3),
    // Параллельные HTTP-запросы внутри одного краула (потоки). 1 = как раньше.
    'max_concurrency' => (int) env('SITE_AUDIT_MAX_CONCURRENCY', 8),
    // Порция обхода в одном job (страниц / секунд). Дальше — ContinueSiteAuditCrawlJob.
    'batch_max_pages' => (int) env('SITE_AUDIT_BATCH_PAGES', 80),
    'batch_max_seconds' => (int) env('SITE_AUDIT_BATCH_SECONDS', 240),
    // Активный краул без updated_at дольше N мин → failed (иначе держит слот навечно)
    'stale_active_minutes' => (int) env('SITE_AUDIT_STALE_ACTIVE_MINUTES', 120),
    // Раньше reclaim: если цепочка Continue/Discover оборвалась — пнуть job снова
    'kick_idle_minutes' => (int) env('SITE_AUDIT_KICK_IDLE_MINUTES', 5),
    // Агрегация большими пачками не влезает в timeout → тики/этапы + пауза (разгрузка БД/CPU)
    'aggregate_tick_seconds' => (float) env('SITE_AUDIT_AGG_TICK_SECONDS', 150),
    'aggregate_tick_pause_seconds' => (int) env('SITE_AUDIT_AGG_TICK_PAUSE', 3),
    'aggregate_job_timeout' => (int) env('SITE_AUDIT_AGG_JOB_TIMEOUT', 600),
    /** Сколько раз failed() перекидывает aggregate job, прежде чем failed краул */
    'aggregate_job_fail_retries' => (int) env('SITE_AUDIT_AGG_JOB_FAIL_RETRIES', 40),
    'aggregate_from_pages_chunk' => (int) env('SITE_AUDIT_AGG_FROM_PAGES_CHUNK', 200),
    'aggregate_broken_links_chunk' => (int) env('SITE_AUDIT_AGG_BROKEN_CHUNK', 250),
    // local/тесты: не резать по тарифу, пока UI/модуль сырые
    'bypass_limits' => (bool) env('SITE_AUDIT_BYPASS_LIMITS', false),
    'thin_words' => (int) env('SITE_AUDIT_THIN_WORDS', 150),
    'title_min' => (int) env('SITE_AUDIT_TITLE_MIN', 30),
    'title_max' => (int) env('SITE_AUDIT_TITLE_MAX', 70),
    'description_min' => (int) env('SITE_AUDIT_DESC_MIN', 70),
    'description_max' => (int) env('SITE_AUDIT_DESC_MAX', 160),
    // сколько детальных краулов хранить на проект (старше — prune)
    'history_keep_per_project' => (int) env('SITE_AUDIT_HISTORY_KEEP', 200),
    // После перехода с платного на Free — через N дней удаляем всю историю аудита
    'free_history_keep_days' => (int) env('SITE_AUDIT_FREE_HISTORY_DAYS', 14),
    // Повторный краул: если content_hash+status совпали с прошлым done — пропускаем HEAD картинок/ассетов
    'incremental_by_content_hash' => (bool) env('SITE_AUDIT_INCREMENTAL', true),
    'robots_max_bytes' => (int) env('SITE_AUDIT_ROBOTS_MAX_BYTES', 512000),
    'simhash_hamming_max' => (int) env('SITE_AUDIT_SIMHASH_HAMMING', 6),
    // Второй проход: 5-граммы. Кандидат с Hamming≤max остаётся только если доля общих шинголов ≥ порога.
    'simhash_shingle_size' => (int) env('SITE_AUDIT_SIMHASH_SHINGLE_SIZE', 5),
    // 0.15: при общем меню 10% слишком легко набиралось на шаблоне.
    'simhash_shingle_min_overlap' => (float) env('SITE_AUDIT_SIMHASH_SHINGLE_OVERLAP', 0.15),
    'simhash_shingle_store_max' => (int) env('SITE_AUDIT_SIMHASH_SHINGLE_STORE', 120),
    'simhash_max_pairs' => (int) env('SITE_AUDIT_SIMHASH_MAX_PAIRS', 200),
    // Токен на ≥ этой доли страниц = шаблон (меню/бренд) — не считаем «смысловым» пересечением.
    'simhash_chrome_token_share' => (float) env('SITE_AUDIT_SIMHASH_CHROME_SHARE', 0.20),
    'simhash_chrome_min_pages' => (int) env('SITE_AUDIT_SIMHASH_CHROME_MIN', 8),
    // Минимум нешаблонных общих слов (раньше 2 — на тощем стенде шумели deep/meta).
    'simhash_min_unique_shared' => (int) env('SITE_AUDIT_SIMHASH_MIN_UNIQUE', 4),
    // Для обеих страниц < thin_words — ещё жёстче (иначе меню+пара слов = «похоже»).
    'simhash_min_unique_shared_thin' => (int) env('SITE_AUDIT_SIMHASH_MIN_UNIQUE_THIN', 10),
    'share_ttl_days' => (int) env('SITE_AUDIT_SHARE_TTL_DAYS', 0), // 0 = бессрочно
    'broken_link_head_max' => (int) env('SITE_AUDIT_BROKEN_HEAD_MAX', 40),
    'broken_external_head_max' => (int) env('SITE_AUDIT_BROKEN_EXT_HEAD_MAX', 80),
    'broken_external_max_findings' => (int) env('SITE_AUDIT_BROKEN_EXT_MAX', 200),
    'aggregate_broken_external_chunk' => (int) env('SITE_AUDIT_BROKEN_EXT_CHUNK', 150),
    'broken_link_max_findings' => (int) env('SITE_AUDIT_BROKEN_MAX_FINDINGS', 200),
    // Уникальные img URL на краул (раньше 500 — «хвост» инвентаря без кода/размера).
    'broken_image_head_max' => (int) env('SITE_AUDIT_BROKEN_IMAGE_HEAD_MAX', 8000),
    'aggregate_image_head_chunk' => (int) env('SITE_AUDIT_IMAGE_HEAD_CHUNK', 80),
    'heavy_image_bytes' => (int) env('SITE_AUDIT_HEAVY_IMAGE_BYTES', 500000),
    'html_critical_min' => (int) env('SITE_AUDIT_HTML_CRITICAL_MIN', 1),
    // Чекер разметки: libxml (быстрый) | html5 (Nu Html Checker / vnu HTTP).
    // Пустой SITE_AUDIT_HTML_CHECKER → html5 если задан VNU_URL, иначе libxml.
    'html_checker_default' => strtolower(trim((string) env('SITE_AUDIT_HTML_CHECKER', ''))),
    // Nu Html Checker HTTP, напр. http://127.0.0.1:8888/ — пусто = HTML5 недоступен
    'vnu_url' => trim((string) env('SITE_AUDIT_VNU_URL', '')),
    'vnu_timeout' => (float) env('SITE_AUDIT_VNU_TIMEOUT', 8),
    'vnu_connect_timeout' => (float) env('SITE_AUDIT_VNU_CONNECT_TIMEOUT', 2),
    'vnu_max_bytes' => (int) env('SITE_AUDIT_VNU_MAX_BYTES', 1_500_000),
    'vnu_sample_max' => (int) env('SITE_AUDIT_VNU_SAMPLE_MAX', 10),
    // Параллельные POST к vnu внутри волны. 0 = как concurrency краула.
    'vnu_concurrency' => (int) env('SITE_AUDIT_VNU_CONCURRENCY', 0),

    'lost_file_head_max' => (int) env('SITE_AUDIT_LOST_FILE_HEAD_MAX', 40),
    'lost_file_max_findings' => (int) env('SITE_AUDIT_LOST_FILE_MAX', 80),
    'error_spike_min_count' => (int) env('SITE_AUDIT_ERROR_SPIKE_MIN', 5),
    'error_spike_status_share' => (float) env('SITE_AUDIT_ERROR_SPIKE_STATUS_SHARE', 0.4),
    'error_spike_path_min' => (int) env('SITE_AUDIT_ERROR_SPIKE_PATH_MIN', 5),
    'error_spike_path_rate' => (float) env('SITE_AUDIT_ERROR_SPIKE_PATH_RATE', 0.5),
    'error_spike_delta_min' => (int) env('SITE_AUDIT_ERROR_SPIKE_DELTA_MIN', 5),
    'error_spike_delta_ratio' => (float) env('SITE_AUDIT_ERROR_SPIKE_DELTA_RATIO', 2.0),
    'click_depth_warn' => (int) env('SITE_AUDIT_CLICK_DEPTH_WARN', 4),
    'strong_max' => (int) env('SITE_AUDIT_STRONG_MAX', 20),
    'nausea_classic_max' => (float) env('SITE_AUDIT_NAUSEA_CLASSIC_MAX', 8.0),
    // Академическая тошнота на коротком «уникальном» тексте ≈ 100/√n — порог 10% ловит почти всё.
    'nausea_academic_max' => (float) env('SITE_AUDIT_NAUSEA_ACADEMIC_MAX', 25.0),
    // Ниже — thin_content; тошнота на 10–40 словах бессмысленна.
    'nausea_min_words' => (int) env('SITE_AUDIT_NAUSEA_MIN_WORDS', 50),
    'bigram_spam_min' => (int) env('SITE_AUDIT_BIGRAM_SPAM_MIN', 5),
    'bigram_spam_density_min' => (float) env('SITE_AUDIT_BIGRAM_SPAM_DENSITY', 1.5),
    'trigram_spam_min' => (int) env('SITE_AUDIT_TRIGRAM_SPAM_MIN', 5),
    'trigram_spam_density_min' => (float) env('SITE_AUDIT_TRIGRAM_SPAM_DENSITY', 1.0),
    // Би-/триграммы на тощих страницах и сквозной бренд в шапке — шум.
    'ngram_spam_min_words' => (int) env('SITE_AUDIT_NGRAM_SPAM_MIN_WORDS', 40),
    'ngram_chrome_share' => (float) env('SITE_AUDIT_NGRAM_CHROME_SHARE', 0.20),
    'ngram_chrome_min_pages' => (int) env('SITE_AUDIT_NGRAM_CHROME_MIN', 8),
    'sitemap_url_cap' => (int) env('SITE_AUDIT_SITEMAP_URL_CAP', 20000),
    'sitemap_not_crawled_sample' => (int) env('SITE_AUDIT_SITEMAP_NOT_CRAWLED_SAMPLE', 80),
    'not_in_sitemap_max' => (int) env('SITE_AUDIT_NOT_IN_SITEMAP_MAX', 500),
    'landing_findings_max' => (int) env('SITE_AUDIT_LANDING_FINDINGS_MAX', 300),
    // Доступность: доля unreachable+5xx среди страниц проверки
    'availability_fail_rate' => (float) env('SITE_AUDIT_AVAILABILITY_FAIL_RATE', 0.10),
    // Индекс ПС vs краул — только Яндекс.Вебмастер (GSC позже). XML site: не используем.
    'serp_index_enabled' => (bool) env('SITE_AUDIT_SERP_INDEX', false),
    'serp_index_engines' => ['yandex'],
    'serp_index_ratio_low' => (float) env('SITE_AUDIT_SERP_INDEX_RATIO_LOW', 0.5),
    'serp_index_ratio_high' => (float) env('SITE_AUDIT_SERP_INDEX_RATIO_HIGH', 3.0),
    'serp_index_prefer_webmaster' => (bool) env('SITE_AUDIT_SERP_INDEX_WEBMASTER', true),
    'serp_index_webmaster_max' => (int) env('SITE_AUDIT_SERP_INDEX_WM_MAX', 50000),
    'serp_index_xml_fallback' => (bool) env('SITE_AUDIT_SERP_INDEX_XML_FALLBACK', false),
    // Сколько URL «нет в индексе» писать отдельными findings (полный список в отчёте)
    'serp_index_url_findings_max' => (int) env('SITE_AUDIT_SERP_INDEX_URL_MAX', 5000),
    // Сколько URL «в индексе, не в проверке» хранить в progress для разбора в UI
    'serp_index_extra_urls_max' => (int) env('SITE_AUDIT_SERP_INDEX_EXTRA_MAX', 5000),
    'serp_index_list_max' => (int) env('SITE_AUDIT_SERP_INDEX_LIST_MAX', 200),
    'serp_index_deep_sample' => (int) env('SITE_AUDIT_SERP_INDEX_DEEP', 20), // legacy
    'serp_index_deep_engine' => env('SITE_AUDIT_SERP_INDEX_DEEP_ENGINE', 'yandex'),

    // Сниппеты ПС: один XML-пакет на URL (SiteAuditSerpUrlBatch) → отчёты сниппеты/TITLE/источник.
    // По умолчанию вкл. Выкл.: SITE_AUDIT_SERP_SNIPPETS=0
    'serp_snippets_enabled' => (bool) env('SITE_AUDIT_SERP_SNIPPETS', true),
    'serp_snippets_engines' => ['yandex', 'google'],
    'serp_snippets_max_urls' => (int) env('SITE_AUDIT_SERP_SNIPPETS_MAX', 30),
    // Каннибализация по живым сниппетам (по умолчанию тот же gate, что SERP-сниппеты)
    'serp_cannibalization_enabled' => (bool) env(
        'SITE_AUDIT_SERP_CANNIBALIZATION',
        env('SITE_AUDIT_SERP_SNIPPETS', true)
    ),
    'serp_cannibalization_max_queries' => (int) env('SITE_AUDIT_SERP_CANNIBAL_MAX', 20),
    'serp_cannibalization_depth' => (int) env('SITE_AUDIT_SERP_CANNIBAL_DEPTH', 20),
    'serp_cannibalization_engines' => ['yandex'],
    'serp_cannibalization_yandex_lr' => env('SITE_AUDIT_SERP_CANNIBAL_LR', '213'),

    // PSI: те же URL, что SERP-пакет (SiteAuditSerpUrlBatch::sampleUrls), лимит = serp_snippets_max_urls по умолчанию.
    'psi_enabled' => (bool) env('SITE_AUDIT_PSI', true),
    'psi_api_key' => env('SITE_AUDIT_PSI_API_KEY', ''),
    'psi_max_urls' => (int) env('SITE_AUDIT_PSI_MAX_URLS', 30),
    'psi_strategies' => ['mobile', 'desktop'],
    'psi_score_warn' => (float) env('SITE_AUDIT_PSI_SCORE_WARN', 0.5),
    'psi_timeout' => (int) env('SITE_AUDIT_PSI_TIMEOUT', 75),
    // 1 URL/тик: rich PSI (4 категории × mobile/desktop) иначе тик легко вылезает за budget.
    'psi_urls_per_tick' => (int) env('SITE_AUDIT_PSI_URLS_PER_TICK', 1),
    // Ориентир ETA в истории: секунд на 1 URL (mobile+desktop) на этапе PSI.
    'psi_eta_seconds_per_url' => (int) env('SITE_AUDIT_PSI_ETA_SEC_PER_URL', 55),

    // Content risk lite: словари топ-15 языков веба (не ML).
    // Языки: ru, en, uk, de, fr, es, pt, it, pl, tr, zh, ja, ko, ar, id.
    'content_risk_enabled' => (bool) env('SITE_AUDIT_CONTENT_RISK', true),
    'content_risk_adult_min_hits' => (int) env('SITE_AUDIT_ADULT_MIN_HITS', 2),
    'content_risk_negative_min_hits' => (int) env('SITE_AUDIT_NEGATIVE_MIN_HITS', 2),
    'word_repeat_min_len' => (int) env('SITE_AUDIT_WORD_REPEAT_MIN_LEN', 4),
    'word_repeat_min_count' => (int) env('SITE_AUDIT_WORD_REPEAT_MIN_COUNT', 3),
    'content_risk_adult' => [
        // ru
        'порно', 'порнуха', 'порнограф', 'эротика', 'сексшоп', 'секс-шоп', 'секс шоп',
        'эскорт', 'интим-услуги', 'интим услуги', 'проститут', 'проституц',
        // en
        'porn', 'pornography', 'xxx', 'erotica', 'sex shop', 'sexshop', 'escort',
        'webcam', 'camsoda', 'onlyfans', 'hentai', 'nsfw', 'camgirl', 'prostitut',
        // uk
        'порнографія', 'еротика', 'секс-шоп', 'ескорт', 'інтим-послуги', 'проституція', 'проститут',
        // de
        'porno', 'pornografie', 'erotik', 'sexshop', 'sex-shop', 'escortservice', 'prostituierte',
        // fr
        'pornographie', 'érotique', 'erotique', 'sexshop', 'escort girl', 'prostituée', 'prostituee',
        // es
        'pornografía', 'pornografia', 'erótica', 'erotica', 'sexshop', 'prostituta', 'prostitución',
        // pt
        'pornografia', 'erótica', 'erotica', 'sex shop', 'prostituta', 'prostituição', 'prostituicao',
        // it
        'pornografia', 'erotismo', 'sex shop', 'escort', 'prostituta', 'prostituzione',
        // pl
        'pornografia', 'erotyka', 'sex shop', 'seks-shop', 'prostytucja', 'prostytutka',
        // tr
        'porno', 'pornografi', 'erotik', 'seks shop', 'eskort', 'fahişe', 'fahise', 'orospu',
        // zh (简体)
        '色情', '黄色网站', '成人视频', '成人影片', '援交', '卖淫', '色情片',
        // ja
        'ポルノ', 'アダルト', 'エロ動画', '風俗', '援交', '売春',
        // ko
        '포르노', '야동', '성인영상', '성인물', '원조교제', '성매매',
        // ar
        'إباحية', 'اباحية', 'بورنو', 'قحبة', 'دعارة', 'جنس للكبار',
        // id
        'pornografi', 'bokep', 'video dewasa', 'seks bebas', 'pelacur', 'prostitusi',
    ],
    'content_risk_negative' => [
        // ru
        'суицид', 'самоубийство', 'самоубийств', 'наркотик', 'наркотики', 'героин', 'кокаин',
        'амфетамин', 'спайс', 'мефедрон', 'взрывчатка', 'взрывчатки', 'терроризм', 'террорист',
        'террористы', 'убийство', 'убийства', 'расчленение', 'расчленен', 'педофил', 'педофилия',
        'насилие над',
        // en
        'suicide', 'suicidal', 'heroin', 'cocaine', 'amphetamine', 'methamphetamine',
        'terrorism', 'terrorist', 'beheading', 'pedophile', 'paedophile', 'pedophilia',
        'child porn', 'explosive device', 'bomb making',
        // uk
        'суїцид', 'самогубство', 'наркотик', 'героїн', 'кокаїн', 'тероризм', 'терорист',
        'вбивство', 'педофіл', 'педофілія', 'вибухівка',
        // de
        'selbstmord', 'suizid', 'heroine', 'kokain', 'amphetamine', 'terrorismus', 'terrorist',
        'mord', 'pädophil', 'paedophil', 'kindesmissbrauch', 'sprengstoff',
        // fr
        'suicide', 'suicidaire', 'héroïne', 'heroine', 'cocaïne', 'cocaine', 'amphétamine',
        'terrorisme', 'terroriste', 'meurtre', 'pédophile', 'pedophile', 'pédophilie', 'explosif',
        // es
        'suicidio', 'heroína', 'heroina', 'cocaína', 'cocaina', 'anfetamina', 'terrorismo',
        'terrorista', 'asesinato', 'pedófilo', 'pedofilo', 'pedofilia', 'explosivo',
        // pt
        'suicídio', 'suicidio', 'heroína', 'heroina', 'cocaína', 'cocaina', 'anfetamina',
        'terrorismo', 'terrorista', 'assassinato', 'pedófilo', 'pedofilo', 'pedofilia', 'explosivo',
        // it
        'suicidio', 'eroina', 'cocaina', 'anfetamina', 'terrorismo', 'terrorista',
        'omicidio', 'pedofilo', 'pedofilia', 'esplosivo',
        // pl
        'samobójstwo', 'samobojstwo', 'heroina', 'kokaina', 'amfetamina', 'terroryzm', 'terrorysta',
        'morderstwo', 'pedofil', 'pedofilia', 'materiał wybuchowy', 'material wybuchowy',
        // tr
        'intihar', 'eroin', 'kokain', 'amfetamin', 'terörizm', 'terorizm', 'terörist', 'terorist',
        'cinayet', 'pedofil', 'patlayıcı', 'patlayici',
        // zh
        '自杀', '自殺', '海洛因', '可卡因', '冰毒', '恐怖主义', '恐怖分子', '谋杀', '恋童', '爆炸物',
        // ja
        '自殺', 'ヘロイン', 'コカイン', '覚醒剤', 'テロリズム', 'テロリスト', '殺人', '児童ポルノ', '爆弾',
        // ko
        '자살', '헤로인', '코카인', '필로폰', '테러리즘', '테러리스트', '살인', '아동성애', '폭발물',
        // ar
        'انتحار', 'هيروين', 'كوكايين', 'إرهاب', 'ارهاب', 'إرهابي', 'ارهابي', 'قتل', 'اعتداء جنسي على الأطفال', 'متفجرات',
        // id
        'bunuh diri', 'heroin', 'kokain', 'amfetamin', 'terorisme', 'teroris',
        'pembunuhan', 'pedofil', 'bahan peledak',
    ],
    // Внешний антиплагиат (вкладка): Titlo TextUniqueness, выборочный запуск
    'plagiarism_external_max_urls' => (int) env('SITE_AUDIT_PLAGIARISM_EXTERNAL_MAX', 20),
    'plagiarism_external_warn_below' => (float) env('SITE_AUDIT_PLAGIARISM_WARN_BELOW', 70),
    'plagiarism_external_engine' => env('SITE_AUDIT_PLAGIARISM_ENGINE', 'yandex'),
    'plagiarism_external_yandex_lr' => env('SITE_AUDIT_PLAGIARISM_LR', '213'),
    // Сколько URL сразу в списке выбора (не весь обход — иначе DOM ляжет на десятках тысяч)
    'plagiarism_external_candidates_max' => (int) env('SITE_AUDIT_PLAGIARISM_CANDIDATES_MAX', 150),
    // Лимит результатов серверного поиска по URL/title
    'plagiarism_external_search_max' => (int) env('SITE_AUDIT_PLAGIARISM_SEARCH_MAX', 100),
    // Автовыборка после обхода: главная + категория + товар/услуга (~3 URL)
    'plagiarism_external_auto' => (bool) env('SITE_AUDIT_PLAGIARISM_AUTO', true),
    'plagiarism_external_auto_max' => (int) env('SITE_AUDIT_PLAGIARISM_AUTO_MAX', 3),
    // Маркер для ProbeStatus: всегда «ручной» допинг поверх авто (не путать с auto-флагом).
    'plagiarism_external_manual' => true,
    'cannibalization_max' => (int) env('SITE_AUDIT_CANNIBALIZATION_MAX', 200),
    'cannibalization_min_token' => (int) env('SITE_AUDIT_CANNIBAL_MIN_TOKEN', 4),
    'cannibalization_min_hits' => (int) env('SITE_AUDIT_CANNIBAL_MIN_HITS', 2),
    'ad_cannibalization_max' => (int) env('SITE_AUDIT_AD_CANNIBAL_MAX', 200),
    'ad_cannibalization_thin_words' => (int) env('SITE_AUDIT_AD_CANNIBAL_THIN', 150),
    'landing_query_match_max' => (int) env('SITE_AUDIT_LANDING_QUERY_MAX', 300),
    'landing_query_min_hits' => (int) env('SITE_AUDIT_LANDING_QUERY_MIN_HITS', 2),
    'landing_query_min_share' => (float) env('SITE_AUDIT_LANDING_QUERY_MIN_SHARE', 0.5),
    'action_plan_max_items' => (int) env('SITE_AUDIT_ACTION_PLAN_MAX', 25),
    'action_plan_ai_enabled' => (bool) env('SITE_AUDIT_ACTION_PLAN_AI', true),

    // Хосты/пути партнёрских сетей (probable_affiliate)
    'affiliate_networks' => [
        'admitad' => ['admitad.com', 'ad.admitad', 'admitad'],
        'actionpay' => ['actionpay.ru', 'actionpay'],
        'gdeslon' => ['gdeslon.ru', 'gdeslon'],
        'cityads' => ['cityads.com', 'cityads'],
        'advertise' => ['advertise.ru'],
        'tradetracker' => ['tradetracker.com'],
        'awin' => ['awin.com', 'awin1.com'],
        'cj' => ['cj.com', 'dpbolvw.net', 'anrdoezrs.net'],
        'amazon' => ['amazon.com/gp/product', 'amzn.to', 'amazon.ru'],
        'generic' => ['/affiliate', 'partner_id=', 'aff_id=', 'click.php', 'go.php?'],
    ],

    'no_outbound_internal_max' => (int) env('SITE_AUDIT_NO_OUTBOUND_MAX', 500),
    'risky_query_max' => (int) env('SITE_AUDIT_RISKY_QUERY_MAX', 300),
    'pagination_param_max' => (int) env('SITE_AUDIT_PAGINATION_PARAM_MAX', 300),
    'risky_query_key_count' => (int) env('SITE_AUDIT_RISKY_QUERY_KEYS', 8),
    'risky_query_len' => (int) env('SITE_AUDIT_RISKY_QUERY_LEN', 120),
    'risky_query_keys' => [
        'phpsessid', 'sid', 'sessionid', 'session_id', 'jsessionid',
        'sort', 'order', 'orderby', 'sortby',
    ],
    'pagination_query_keys' => [
        'page', 'p', 'pagen_1', 'paged', 'offset', 'start',
    ],
    'facet_query_keys' => [
        'filter', 'filters', 'facet', 'facets',
    ],
    'soft_404_title_patterns' => [
        '404',
        'not found',
        'page not found',
        'страница не найдена',
        'не найдена',
        'ошибка 404',
    ],

    /*
    | Коды, попадающие в SEO-сводку (остальные — tech).
    */
    'seo_codes' => [
        'duplicate_title',
        'duplicate_description',
        'duplicate_content',
        'similar_pages',
        'empty_title',
        'empty_description',
        'multiple_title_or_description',
        'noindex',
        'indexing_blocked',
        'canonical_foreign',
        'canonical_empty',
        'canonical_not_self',
        'multiple_canonical',
        'pages_with_canonical',
        'missing_h1',
        'multiple_h1',
        'thin_content',
        'title_too_short',
        'title_too_long',
        'description_too_short',
        'description_too_long',
        'title_equals_h1',
        'title_equals_description',
        'description_equals_h1',
        'h1_equals_h2',
        'heading_hierarchy',
        'too_many_strong',
        'duplicate_links',
        'external_links',
        'meta_spam',
        'h1_spam',
        'text_nausea',
        'text_bigram_spam',
        'text_trigram_spam',
        'no_unique_images',
        'text_in_noindex',
        'landing_not_in_sitemap',
        'landing_not_crawled',
        'landing_url_changed',
        'landing_plagiarism_external',
        'landing_no_inbound_internal',
        'keyword_cannibalization',
        'ad_cannibalization',
        'serp_snippet_cannibalization',
        'landing_query_mismatch',
        'commercial_missing_contacts',
        'commercial_missing_price',
        'commercial_missing_cta',
        'commercial_missing_delivery',
        'commercial_missing_payment',
        'commercial_missing_stock',
        'commercial_missing_reviews',
        'adult_content',
        'negative_content',
        'word_repeat_in_sentence',
        'robots_txt_closed',
        'robots_blocked',
        'meta_nofollow',
        'soft_404',
        'orphan_pages',
        'duplicate_url_variants',
        'www_both_available',
        'http_https_both_available',
        'page_has_broken_links',
        'broken_internal_link',
        'broken_external_link',
        'deep_pages',
        'site_availability',
            'index_count_mismatch',
            'serp_snippets',
            'serp_title_mismatch',
        'serp_snippet_source',
        'serp_snippet_cannibalization',
        'probable_affiliate',
        'seo_meta_errors',
        'multiple_canonical',
        'no_outbound_internal',
        'risky_query_params',
        'pagination_param',
    ],

    /*
    | Пресеты скорости (запросов в секунду на хост).
    | slow ≈ осторожно против антибота, turbo — только свои/тестовые сайты.
    */
    'speed_presets' => [
        'slow' => 1.0,
        'normal' => 5.0,
        'fast' => 10.0,
        'turbo' => 15.0,
    ],

    /*
    | Пул UA под ротацию (реальные браузеры). Не светим TitloBot по умолчанию.
    */
    'user_agents' => [
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36',
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36',
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0',
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0',
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0',
        'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0',
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15',
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15',
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0',
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0',
        'Mozilla/5.0 (iPhone; CPU iPhone OS 17_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2 Mobile/15E148 Safari/604.1',
        'Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1',
        'Mozilla/5.0 (Linux; Android 14; Pixel 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Mobile Safari/537.36',
        'Mozilla/5.0 (Linux; Android 13; SM-S918B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Mobile Safari/537.36',
        'Mozilla/5.0 (Linux; Android 12; Pixel 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36',
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
    ],

    'findings' => [
        // —— Фаза A (MVP) ——
        'http_4xx' => [
            'phase' => 'A',
            'severity' => 'critical',
            'title' => 'Ошибки 4xx',
            'description' => 'Страница отвечает клиентской ошибкой (404, 403 и т.п.).',
        ],
        'http_5xx' => [
            'phase' => 'A',
            'severity' => 'critical',
            'title' => 'Ошибки 5xx',
            'description' => 'Страница отвечает серверной ошибкой (500, 502, 503…).',
        ],
        'unreachable' => [
            'phase' => 'A',
            'severity' => 'critical',
            'title' => 'Недоступные страницы',
            'description' => 'Не удалось получить ответ (timeout, DNS, connection error).',
        ],
        'redirect' => [
            'phase' => 'A',
            'severity' => 'warning',
            'title' => 'Редиректы',
            'description' => 'URL отвечает редиректом на другой адрес.',
            'group' => 'tech',
        ],
        'redirect_chain_long' => [
            'phase' => 'A',
            'severity' => 'other',
            'title' => 'Множественные редиректы',
            'description' => 'Слишком длинная цепочка редиректов.',
            'group' => 'tech',
        ],
        'redirect_loop' => [
            'phase' => 'A',
            'severity' => 'critical',
            'title' => 'Циклические редиректы',
            'description' => 'Цепочка редиректов зацикливается (URL повторяется) — страница недоступна.',
            'group' => 'tech',
        ],
        'duplicate_title' => [
            'phase' => 'A',
            'severity' => 'critical',
            'title' => 'Дубли TITLE',
            'description' => 'Несколько страниц с одинаковым TITLE.',
        ],
        'duplicate_description' => [
            'phase' => 'A',
            'severity' => 'critical',
            'title' => 'Дубли Description',
            'description' => 'Несколько страниц с одинаковым Description.',
        ],
        'duplicate_content' => [
            'phase' => 'B',
            'severity' => 'critical',
            'title' => 'Дубли контента',
            'description' => 'Несколько страниц с одинаковым текстовым content_hash.',
        ],
        'similar_pages' => [
            'phase' => 'B',
            'severity' => 'important',
            'title' => 'Похожие страницы',
            'description' => 'Похожие по тексту: SimHash + фильтр 5-грамм, пара A/B, общие слова/фразы.',
        ],
        'empty_title' => [
            'phase' => 'A',
            'severity' => 'critical',
            'title' => 'Пустой TITLE',
            'description' => 'На странице отсутствует или пуст тег title.',
        ],
        'empty_description' => [
            'phase' => 'A',
            'severity' => 'critical',
            'title' => 'Пустой Description',
            'description' => 'Отсутствует meta description.',
        ],
        'multiple_title_or_description' => [
            'phase' => 'A',
            'severity' => 'critical',
            'title' => 'Несколько title/description',
            'description' => 'В HTML больше одного title или meta description.',
        ],
        'noindex' => [
            'phase' => 'A',
            'severity' => 'warning',
            'title' => 'Страницы с noindex',
            'description' => 'Закрыто meta name="robots" и/или HTTP X-Robots-Tag (не robots.txt).',
        ],
        'canonical_foreign' => [
            'phase' => 'A',
            'severity' => 'other',
            'title' => 'Canonical на чужой домен',
            'description' => 'rel=canonical указывает на другой хост.',
        ],
        'canonical_not_self' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Canonical не на себя',
            'description' => 'rel=canonical указывает на другой URL того же сайта (не self-canonical).',
        ],
        'canonical_empty' => [
            'phase' => 'A',
            'severity' => 'info',
            'title' => 'Страницы без canonical',
            'description' => 'Нет rel=canonical — сложнее указать поисковику предпочтительный URL при дублях и параметрах.',
        ],
        'multiple_canonical' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Несколько rel=canonical',
            'description' => 'В HTML больше одного link rel=canonical.',
        ],
        'seo_meta_errors' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'SEO-ошибки META тегов',
            'description' => 'Сводный отчёт по ошибкам title/description/canonical и связанным META-сигналам (стык с модулем мета-тегов без повторного HTTP).',
            'virtual' => true,
            'codes' => [
                'empty_title',
                'empty_description',
                'multiple_title_or_description',
                'multiple_canonical',
                'canonical_not_self',
                'title_too_short',
                'title_too_long',
                'description_too_short',
                'description_too_long',
                'title_equals_h1',
                'title_equals_description',
                'description_equals_h1',
                'meta_spam',
            ],
        ],
        'page_too_large' => [
            'phase' => 'A',
            'severity' => 'warning',
            'title' => 'Очень большие страницы',
            'description' => 'Размер ответа превышает порог.',
        ],
        'missing_h1' => [
            'phase' => 'A',
            'severity' => 'warning',
            'title' => 'Страницы без H1',
            'description' => 'На странице нет заголовка H1.',
        ],
        'multiple_h1' => [
            'phase' => 'A',
            'severity' => 'critical',
            'title' => 'Несколько H1',
            'description' => 'На странице больше одного H1.',
        ],
        'thin_content' => [
            'phase' => 'A',
            'severity' => 'warning',
            'title' => 'Тощие страницы',
            'description' => 'Мало текстового контента (ниже порога по числу слов).',
        ],
        'title_too_short' => [
            'phase' => 'A',
            'severity' => 'important',
            'title' => 'Короткий TITLE',
            'description' => 'TITLE короче рекомендуемой длины.',
        ],
        'title_too_long' => [
            'phase' => 'A',
            'severity' => 'important',
            'title' => 'Длинный TITLE',
            'description' => 'TITLE длиннее рекомендуемой длины.',
        ],
        'description_too_short' => [
            'phase' => 'A',
            'severity' => 'warning',
            'title' => 'Короткий Description',
            'description' => 'Description короче рекомендуемой длины.',
        ],
        'description_too_long' => [
            'phase' => 'A',
            'severity' => 'warning',
            'title' => 'Длинный Description',
            'description' => 'Description длиннее рекомендуемой длины.',
        ],
        'title_equals_h1' => [
            'phase' => 'A',
            'severity' => 'important',
            'title' => 'TITLE = H1',
            'description' => 'TITLE совпадает с H1.',
        ],
        'title_equals_description' => [
            'phase' => 'A',
            'severity' => 'important',
            'title' => 'TITLE = Description',
            'description' => 'TITLE совпадает с Description.',
        ],
        'description_equals_h1' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'DESCRIPTION = H1',
            'description' => 'Meta description совпадает с H1.',
        ],
        'h1_equals_h2' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'H1 = H2',
            'description' => 'Текст H1 совпадает с одним из H2.',
        ],
        'heading_hierarchy' => [
            'phase' => 'B',
            'severity' => 'important',
            'title' => 'Нарушена иерархия заголовков',
            'description' => 'Заголовок до первого H1 или пропуск уровня (например H1→H3) в outline h1–h6.',
            'group' => 'seo',
        ],
        'too_many_strong' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Много strong/b',
            'description' => 'На странице слишком много тегов strong/b (риск переспама выделениями).',
        ],
        'duplicate_links' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Дубли одной ссылки',
            'description' => 'Один и тот же внутренний URL встречается в follow-ссылках страницы несколько раз (nofollow и блоки noindex не считаются).',
        ],
        'external_links' => [
            'phase' => 'B',
            'severity' => 'info',
            'title' => 'Исходящие на другие сайты',
            'description' => 'На странице есть ссылки на внешние домены. В деталях — куда именно.',
        ],
        'meta_spam' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Переспам в META',
            'description' => 'В TITLE или Description одно значимое слово повторяется слишком часто.',
        ],
        'h1_spam' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Переспам в H1',
            'description' => 'В H1 одно значимое слово повторяется слишком часто.',
        ],
        'text_nausea' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Тошнота текста',
            'description' => 'Классическая или академическая тошнота выше порога (на страницах с достаточным объёмом текста).',
        ],
        'text_bigram_spam' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Переспам биграммами',
            'description' => 'Одна и та же биграмма слишком часто встречается в тексте страницы.',
        ],
        'text_trigram_spam' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Переспам триграммами',
            'description' => 'Одна и та же триграмма слишком часто встречается в тексте страницы.',
            'group' => 'seo',
        ],
        'no_unique_images' => [
            'phase' => 'B',
            'severity' => 'info',
            'title' => 'Нет изображений с src',
            'description' => 'На странице нет картинок с нормальным адресом (src), либо img нет совсем.',
        ],
        'text_in_noindex' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Текст в noindex',
            'description' => 'Внутри Яндекс-блоков <!--noindex--> / <noindex> есть текст или ссылки (часто соцсети в шаблоне).',
        ],
        'images_without_alt' => [
            'phase' => 'A',
            'severity' => 'warning',
            'title' => 'Изображения без alt',
            'description' => 'Img без alt или с пустым alt: в деталях превью и src.',
        ],

        // —— Фаза B (lite) ——
        'robots_txt_error' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Ошибки robots.txt',
            'description' => 'Проблемы с файлом robots.txt: недоступен, пустой, слишком большой, битые Sitemap: и т.п.',
        ],
        'robots_txt_closed' => [
            'phase' => 'B',
            'severity' => 'critical',
            'title' => 'Закрытие robots.txt',
            'description' => 'В robots.txt для User-agent: * задано Disallow: / — сайт закрыт от обхода роботов.',
        ],
        'robots_blocked' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'URL закрыт в robots.txt',
            'description' => 'Страница попадает под Disallow в robots.txt.',
        ],
        'indexing_blocked' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Блокировки индексации',
            'description' => 'Сводный отчёт: noindex, закрытие в robots.txt и ошибки robots.txt.',
            'virtual' => true,
            'codes' => ['noindex', 'robots_blocked', 'robots_txt_closed', 'robots_txt_error'],
        ],
        'pages_with_canonical' => [
            'phase' => 'A',
            'severity' => 'info',
            'title' => 'Страницы с rel=canonical',
            'description' => 'Список страниц, у которых задан rel=canonical (и его target).',
            'source' => 'pages_canonical',
        ],
        'crawl_pages' => [
            'phase' => 'A',
            'severity' => 'info',
            'title' => 'Страницы проверки',
            'description' => 'Все страницы, которые скачала эта проверка (не ошибки — инвентарь).',
            'source' => 'pages_all',
            'hidden' => true,
            'inventory' => true,
            'group' => 'tech',
        ],
        'crawl_images' => [
            'phase' => 'A',
            'severity' => 'info',
            'title' => 'Картинки проверки',
            'description' => 'Изображения (img): URL, страница, HTTP-код, вес, Ш×В, тип, внешняя, alt. HEAD по бюджету; до 40 src на страницу.',
            'source' => 'pages_images',
            'hidden' => true,
            'inventory' => true,
            'group' => 'tech',
        ],
        'pages_with_iframe' => [
            'phase' => 'B',
            'severity' => 'info',
            'title' => 'Страницы с frame/iframe',
            'description' => 'В HTML есть frame/iframe — важный контент лучше в основной разметке, виджеты — осознанно.',
        ],
        'mixed_content' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Смешанный контент',
            'description' => 'На HTTPS-странице в HTML есть http:// ресурсы (картинки, скрипты, стили). В деталях — список URL.',
        ],
        'insecure_form' => [
            'phase' => 'B',
            'severity' => 'critical',
            'title' => 'Форма на http с HTTPS-страницы',
            'description' => 'На HTTPS-странице есть form action=http:// — данные уходят без шифрования. Виды «По формам» / «По страницам»; в деталях — id/name/class и фрагмент тега.',
            'group' => 'tech',
        ],
        'bad_doctype' => [
            'phase' => 'B',
            'severity' => 'info',
            'title' => 'Неверный HTML DOCTYPE',
            'description' => 'DOCTYPE отсутствует или выглядит необычно (не HTML5).',
        ],
        'meta_nofollow' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Nofollow (meta)',
            'description' => 'Страница закрыта nofollow в meta robots / X-Robots-Tag.',
        ],
        'links_nofollow' => [
            'phase' => 'B',
            'severity' => 'info',
            'title' => 'Ссылки с nofollow',
            'description' => 'В HTML есть rel=nofollow: анкор и URL. Виды «По ссылкам» / «По страницам».',
        ],
        'external_assets' => [
            'phase' => 'B',
            'severity' => 'info',
            'title' => 'Файлы с внешних сайтов',
            'description' => 'На странице подключены script/css/img с чужого хоста. В деталях — какие файлы и откуда.',
        ],
        'soft_404' => [
            'phase' => 'B',
            'severity' => 'other',
            'title' => 'Soft 404',
            'description' => 'Ответ 200, но в TITLE/H1 есть признаки «не найдено» / 404. Мало текста без таких паттернов — отчёт «Тощие страницы».',
        ],
        'orphan_pages' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Страницы-сироты',
            'description' => 'В рамках проверки нет входящих внутренних ссылок на эту страницу (кроме главной).',
        ],
        'sitemap_missing' => [
            'phase' => 'B',
            'severity' => 'important',
            'title' => 'Sitemap не найден',
            'description' => 'На сайте нет рабочей карты: sitemap.xml / sitemap index / Sitemap: в robots.txt. Не путать с «страница не в sitemap».',
        ],
        'sitemap_error' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Ошибка sitemap',
            'description' => 'Конкретный sitemap недоступен, пустой или не похож на XML.',
        ],
        'not_in_sitemap' => [
            'phase' => 'B',
            'severity' => 'info',
            'title' => 'Страница не в sitemap',
            'description' => 'URL обойден проверкой, но отсутствует в карте сайта (sitemap).',
        ],
        'sitemap_not_crawled' => [
            'phase' => 'B',
            'severity' => 'info',
            'title' => 'В sitemap, не в проверке',
            'description' => 'URL есть в sitemap, но не сохранён в результатах этой проверки (лимит, robots или сбой скачивания). Не путать с ошибкой самой страницы.',
        ],
        'landing_not_in_sitemap' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Посадочная не в sitemap',
            'description' => 'Целевой URL из мониторинга позиций отсутствует в sitemap сайта.',
        ],
        'landing_not_crawled' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Посадочная не в проверке',
            'description' => 'Целевой URL из мониторинга не попал в обход (лимит или нет во внутренних ссылках/sitemap-сиде).',
        ],
        'landing_url_changed' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Изменения URL посадочных',
            'description' => 'Целевой URL (monitoring.page) для запроса изменился относительно предыдущей проверки проекта.',
        ],
        'duplicate_url_variants' => [
            'phase' => 'A',
            'severity' => 'other',
            'title' => 'Дубли URL (www/http/slash)',
            'description' => 'Одна и та же страница доступна под разными вариантами URL (схема, www, слэш).',
        ],
        'www_both_available' => [
            'phase' => 'A',
            'severity' => 'critical',
            'title' => 'Сайт открыт и с www, и без www',
            'description' => 'Оба зеркала (www и без www) отдают контент и не сводятся редиректом на один хост. В деталях — куда уходит каждый вариант и куда настроить 301. Дубль всего сайта — грубое нарушение.',
        ],
        'http_https_both_available' => [
            'phase' => 'A',
            'severity' => 'critical',
            'title' => 'Сайт открыт и по http, и по https',
            'description' => 'HTTP отвечает без редиректа на HTTPS, при этом HTTPS тоже доступен. В деталях — куда должен идти 301. Дубли по схеме — грубое нарушение.',
        ],
        'page_has_broken_links' => [
            'phase' => 'A',
            'severity' => 'warning',
            'title' => 'Страницы с битыми ссылками',
            'description' => 'На странице есть внутренние ссылки на недоступные/ошибочные URL.',
        ],
        'broken_internal_link' => [
            'phase' => 'A',
            'severity' => 'critical',
            'title' => 'Битые внутренние ссылки',
            'description' => 'Целевой URL отвечает 4xx/5xx или недоступен. Одна строка на битый URL; страницы со ссылкой — в «Откуда ссылаются».',
        ],
        'page_has_broken_external_links' => [
            'phase' => 'B',
            'severity' => 'important',
            // Дубль «Битые внешние ссылки» (там же «Откуда ссылаются») — в меню не показываем.
            'hidden' => true,
            'title' => 'Страницы с битыми внешними ссылками',
            'description' => 'На странице есть исходящие ссылки на чужие URL с 4xx/5xx/ошибкой. Сводный список — в «Битые внешние ссылки».',
        ],
        'broken_external_link' => [
            'phase' => 'B',
            'severity' => 'important',
            'title' => 'Битые внешние ссылки',
            'description' => 'Внешний URL отвечает 4xx/5xx или недоступен. Одна строка на битый адрес; страницы со ссылкой — в «Откуда ссылаются».',
        ],
        'page_has_bad_links' => [
            'phase' => 'C',
            'severity' => 'warning',
            'title' => 'Плохие ссылки',
            'description' => 'Ссылки с пустым href, #, javascript: или неразрешимым URL (не HTTP-битые).',
            'group' => 'tech',
        ],
        'html_critical_errors' => [
            'phase' => 'C',
            'severity' => 'other',
            'title' => 'Критические ошибки HTML',
            'description' => 'Сэмпл критичных ошибок разметки (чекер: libxml или HTML5/Nu — выбирается при запуске). Одинаковая ошибка на многих URL = почти всегда сквозной шаблон (шапка/подвал). Смотрите вид «По ошибкам».',
            'group' => 'tech',
        ],
        'lost_file' => [
            'phase' => 'C',
            'severity' => 'warning',
            'title' => 'Потерянные файлы',
            'description' => 'CSS/JS ресурс недоступен (HEAD), с указанием страниц-referrer.',
            'group' => 'tech',
        ],
        'adult_content' => [
            'phase' => 'C',
            'severity' => 'warning',
            'title' => '«Взрослый» контент',
            'description' => 'В тексте страницы найдены слова из списка 18+ (15 языков, поиск по словарю).',
            'group' => 'seo',
        ],
        'negative_content' => [
            'phase' => 'C',
            'severity' => 'warning',
            'title' => 'Негативный контент',
            'description' => 'В тексте найдены слова из «тревожного» списка на 15 языках (насилие, наркотики, терроризм и т.п.).',
            'group' => 'seo',
        ],
        'word_repeat_in_sentence' => [
            'phase' => 'C',
            'severity' => 'info',
            'title' => 'Повторы слова в предложении',
            'description' => 'Одно и то же слово повторяется в предложении выше порога (стилистика / переспам).',
            'group' => 'seo',
        ],
        'landing_plagiarism_external' => [
            'phase' => 'C',
            'severity' => 'warning',
            'title' => 'Низкая уникальность текста (внешний)',
            'description' => 'После обхода сверяем выборку страниц с выдачей. В отчёт — только ниже порога; все проверенные URL с % — в блоке «Проверили» и на вкладке «Антиплагиат».',
            'group' => 'seo',
            'uses_xml' => true,
        ],
        'landing_no_inbound_internal' => [
            'phase' => 'C',
            'severity' => 'warning',
            'title' => 'Нет внутренних ссылок на посадочную',
            'description' => 'На посадочную из мониторинга нет входящих внутренних ссылок в проверке (кроме самоссылок).',
            'group' => 'seo',
        ],
        'keyword_cannibalization' => [
            'phase' => 'C',
            'severity' => 'warning',
            'title' => 'Каннибализация запросов',
            'description' => 'Запрос из мониторинга встречается в title/h1 у страницы, отличной от назначенной посадочной.',
            'group' => 'seo',
        ],
        'ad_cannibalization' => [
            'phase' => 'C',
            'severity' => 'warning',
            'title' => 'Каннибализация рекламой',
            'description' => 'Запрос из мониторинга позиций в TITLE/H1 у страницы, похожей на промо (путь /lp|/promo или тонкая CTA). Без съёма объявлений — эвристика по обходу.',
            'group' => 'seo',
        ],
        'serp_snippet_cannibalization' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Каннибализация по сниппетам (SERP)',
            'description' => 'По запросу мониторинга в ТОП выдачи ≥2 URL вашего сайта (живые сниппеты). Отдельные запросы по фразам (не общий набор из 30 URL).',
            'group' => 'seo',
            'uses_xml' => true,
        ],
        'landing_query_mismatch' => [
            'phase' => 'D',
            'severity' => 'warning',
            'title' => 'Несоответствие запроса посадочной',
            'description' => 'Запрос из мониторинга слабо отражён в title/h1/description назначенной посадочной (lite по мета).',
            'group' => 'seo',
        ],
        'commercial_missing_contacts' => [
            'phase' => 'C',
            'severity' => 'info',
            'title' => 'Телефон / адрес на коммерческих',
            'description' => 'Коммерческая страница без телефона и/или адреса в видимом тексте (эвристика).',
            'group' => 'seo',
        ],
        'commercial_missing_price' => [
            'phase' => 'D',
            'severity' => 'info',
            'title' => 'Нет цены на коммерческой',
            'description' => 'Коммерческая страница без явной цены (₽/руб/«цена») в тексте.',
            'group' => 'seo',
        ],
        'commercial_missing_cta' => [
            'phase' => 'D',
            'severity' => 'info',
            'title' => 'Нет CTA купить/заказать',
            'description' => 'На «коммерческих» страницах (≥40 слов) нет текста CTA: купить / заказать / в корзину и т.п.',
            'group' => 'seo',
        ],
        'commercial_missing_delivery' => [
            'phase' => 'D',
            'severity' => 'info',
            'title' => 'Нет блока доставки',
            'description' => 'Коммерческая страница без слов про доставку/самовывоз в тексте (lite-эвристика).',
            'group' => 'seo',
        ],
        'commercial_missing_payment' => [
            'phase' => 'D',
            'severity' => 'info',
            'title' => 'Нет способов оплаты',
            'description' => 'На «коммерческих» страницах нет слов про оплату (карты, безнал, рассрочка).',
            'group' => 'seo',
        ],
        'commercial_missing_stock' => [
            'phase' => 'D',
            'severity' => 'info',
            'title' => 'Нет статуса наличия',
            'description' => 'Коммерческая страница без «в наличии» / остатка / под заказ.',
            'group' => 'seo',
        ],
        'commercial_missing_reviews' => [
            'phase' => 'D',
            'severity' => 'info',
            'title' => 'Нет отзывов / рейтинга',
            'description' => 'Коммерческая страница без упоминания отзывов или рейтинга.',
            'group' => 'seo',
        ],
        'commercial_factors' => [
            'phase' => 'D',
            'severity' => 'info',
            'title' => 'Коммерческие факторы (lite)',
            'description' => 'Сводка: контакты, цена, CTA, доставка, оплата, наличие, отзывы на коммерческих страницах. Без сравнения с ТОП конкурентов.',
            'virtual' => true,
            'group' => 'seo',
            'codes' => [
                'commercial_missing_contacts',
                'commercial_missing_price',
                'commercial_missing_cta',
                'commercial_missing_delivery',
                'commercial_missing_payment',
                'commercial_missing_stock',
                'commercial_missing_reviews',
            ],
        ],
        'broken_image' => [
            'phase' => 'C',
            'severity' => 'warning',
            'title' => 'Битые изображения',
            'description' => 'img src недоступен (4xx/5xx/ошибка) по HEAD-сэмплу.',
            'group' => 'tech',
        ],
        'heavy_image' => [
            'phase' => 'C',
            'severity' => 'info',
            'title' => 'Слишком тяжёлые изображения',
            'description' => 'Размер картинки (Content-Length) выше порога.',
            'group' => 'tech',
        ],
        'error_spike' => [
            'phase' => 'C',
            'severity' => 'warning',
            'title' => 'Выбросы ошибок',
            'description' => 'Аномалии: кластер одного HTTP-кода, «горящий» префикс URL или скачок ошибок vs прошлая проверка.',
            'group' => 'tech',
        ],
        'psi_mobile' => [
            'phase' => 'C',
            'severity' => 'info',
            'title' => 'Мобильные устройства (PSI)',
            'description' => 'Скорость «как на телефоне»: до 30 URL (тот же набор, что у сниппетов), балл, метрики, рекомендации Google PSI.',
            'group' => 'tech',
        ],
        'psi_desktop' => [
            'phase' => 'C',
            'severity' => 'info',
            'title' => 'Компьютеры (PSI)',
            'description' => 'Скорость «как на компьютере»: до 30 URL (тот же набор, что у сниппетов), балл, метрики, рекомендации Google PSI.',
            'group' => 'tech',
        ],
        'deep_pages' => [
            'phase' => 'B',
            'severity' => 'info',
            'title' => 'Глубокие страницы',
            'description' => 'Далеко от главной по HTML-ссылкам (без JS). Часто листинг на JS — тогда путь идёт через соседние URL.',
        ],
        'site_availability' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Проблемы доступности сайта',
            'description' => 'Корень недоступен/ошибочен или доля unreachable/4xx/5xx среди страниц проверки выше порога.',
        ],
        'index_count_mismatch' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Страницы на сайте не в индексе поисковых',
            'description' => 'Сверка «в поиске» (Вебмастер / GSC) с проверкой: сводка и URL, которых нет в индексе — в деталях указана ПС.',
            'group' => 'seo',
        ],
        'serp_snippets' => [
            'phase' => 'B',
            'severity' => 'info',
            'title' => 'Сниппеты Яндекс / Google',
            'description' => 'Как страница выглядит в поиске: заголовок и текст под ссылкой. Общий набор до 30 URL (с PSI), один съём на адрес.',
            'group' => 'seo',
            'uses_xml' => true,
        ],
        'serp_title_mismatch' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'TITLE страницы ≠ TITLE в выдаче',
            'description' => 'Общий набор до 30 URL: Яндекс и Google. В таблице — все снятые; расхождения и совпадения («всё ок»). В счётчике слева — только проблемы.',
            'group' => 'seo',
            'uses_xml' => true,
        ],
        'serp_snippet_source' => [
            'phase' => 'C',
            'severity' => 'info',
            'title' => 'Подсветка источника сниппета',
            'description' => 'Откуда в выдаче, похоже, взяли заголовок и текст: TITLE, H1, description или «неизвестно». Тот же набор до 30 URL.',
            'group' => 'seo',
            'uses_xml' => true,
        ],
        'probable_affiliate' => [
            'phase' => 'C',
            'severity' => 'info',
            'title' => 'Вероятные аффилиаты',
            'description' => 'На странице есть исходящие ссылки на типичные партнёрские сети / affiliate-паттерны.',
            'group' => 'seo',
        ],
        'no_outbound_internal' => [
            'phase' => 'B',
            'severity' => 'info',
            'title' => 'Страницы без исходящих внутренних',
            'description' => 'У страницы нет исходящих внутренних ссылок в проверке (тупик перелинковки).',
        ],
        'risky_query_params' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Рисковые параметры URL',
            'description' => 'В query есть session/sort или слишком длинный/широкий набор параметров (риск дублей в индексе).',
        ],
        'pagination_param' => [
            'phase' => 'B',
            'severity' => 'info',
            'title' => 'Пагинация / фильтры в URL',
            'description' => 'URL похож на страницу пагинации или facet-фильтра (?page=, /page/N, filter=…).',
        ],
        /*
         * Внешний модуль Titlo: в дереве аудита — страница-объяснение + CTA,
         * не мгновенный редирект и не finding проверки.
         */
        'site_competitors' => [
            'phase' => 'D',
            'severity' => 'info',
            'title' => 'Конкуренты сайта',
            'description' => 'Сравнение с ТОП по запросам — отдельный модуль; аудит сайт не сравнивает с выдачей.',
            'group' => 'seo',
            'external' => true,
            'route' => 'competitor.analysis',
            'external_cta' => 'Открыть анализ конкурентов',
            'related_codes' => [],
            'uses_xml' => true,
        ],
        'site_index_check' => [
            'phase' => 'D',
            'severity' => 'info',
            'title' => 'Проверка индексации',
            'description' => 'Свои списки URL и живые сниппеты — модуль; в аудите уже lite SERP/индекс по проверке.',
            'group' => 'seo',
            'external' => true,
            'route' => 'pages.index-check',
            'external_cta' => 'Открыть проверку индексации',
            'related_codes' => [
                'index_count_mismatch',
                'serp_snippets',
                'serp_title_mismatch',
            ],
            'uses_xml' => true,
        ],
        'site_meta_tags' => [
            'phase' => 'D',
            'severity' => 'info',
            'title' => 'Мониторинг мета-тегов',
            'description' => 'История META во времени — модуль; в аудите snapshot ошибок по этой проверке.',
            'group' => 'seo',
            'external' => true,
            'route' => 'meta-tags.index',
            'external_cta' => 'Открыть мониторинг мета-тегов',
            'related_codes' => ['seo_meta_errors'],
        ],
        'site_esenin' => [
            'phase' => 'D',
            'severity' => 'info',
            'title' => 'Есенин / проверка текста',
            'description' => 'Глубокий разбор текста — модуль; в аудите lite тошнота и n-граммы по HTML проверки.',
            'group' => 'seo',
            'external' => true,
            'route' => 'pages.esenin-text-check',
            'external_cta' => 'Открыть Есенин',
            'related_codes' => [
                'text_nausea',
                'text_bigram_spam',
                'text_trigram_spam',
            ],
        ],
        'site_http_headers' => [
            'phase' => 'D',
            'severity' => 'info',
            'title' => 'HTTP-заголовки',
            'description' => 'Точечная проверка заголовков URL — модуль; в аудите security pack по всей проверке.',
            'group' => 'tech',
            'external' => true,
            'route' => 'pages.headers',
            'external_cta' => 'Открыть HTTP-заголовки',
            'related_codes' => ['security_headers'],
        ],
        'security_headers' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Безопасность (HTTP-заголовки)',
            'description' => 'Сводка: нет HSTS / XFO / XCTO / CSP / Referrer-Policy / Permissions-Policy / COOP / COEP / CORP, insecure forms, mixed content.',
            'virtual' => true,
            'group' => 'tech',
            'codes' => [
                'missing_hsts',
                'missing_x_frame_options',
                'missing_x_content_type_options',
                'missing_csp',
                'missing_referrer_policy',
                'missing_permissions_policy',
                'missing_coop',
                'missing_coep',
                'missing_corp',
                'insecure_form',
                'mixed_content',
            ],
        ],
        'missing_hsts' => [
            'phase' => 'B',
            'severity' => 'warning',
            'title' => 'Нет Strict-Transport-Security',
            'description' => 'На HTTPS-ответе нет заголовка HSTS.',
            'group' => 'tech',
        ],
        'missing_x_frame_options' => [
            'phase' => 'B',
            'severity' => 'info',
            'title' => 'Нет X-Frame-Options',
            'description' => 'Ответ не задаёт X-Frame-Options (риск clickjacking).',
            'group' => 'tech',
        ],
        'missing_x_content_type_options' => [
            'phase' => 'B',
            'severity' => 'info',
            'title' => 'Нет X-Content-Type-Options',
            'description' => 'Нет заголовка X-Content-Type-Options: nosniff — браузер может угадать MIME-тип файла.',
            'group' => 'tech',
        ],
        'missing_csp' => [
            'phase' => 'C',
            'severity' => 'info',
            'title' => 'Нет Content-Security-Policy',
            'description' => 'Нет Content-Security-Policy — браузер не ограничивает, откуда можно грузить скрипты и ресурсы.',
            'group' => 'tech',
        ],
        'missing_referrer_policy' => [
            'phase' => 'C',
            'severity' => 'info',
            'title' => 'Нет Referrer-Policy',
            'description' => 'Нет Referrer-Policy — браузер может отдавать полный URL страницы в Referer на чужие сайты.',
            'group' => 'tech',
        ],
        'missing_permissions_policy' => [
            'phase' => 'C',
            'severity' => 'info',
            'title' => 'Нет Permissions-Policy',
            'description' => 'Ответ не задаёт Permissions-Policy (или legacy Feature-Policy).',
            'group' => 'tech',
        ],
        'missing_coop' => [
            'phase' => 'C',
            'severity' => 'info',
            'description' => 'Нет COOP — вкладка слабее изолирована от window.opener; проверьте перед same-origin (OAuth/попапы).',
            'title' => 'Нет Cross-Origin-Opener-Policy',
            'group' => 'tech',
        ],
        'missing_coep' => [
            'phase' => 'C',
            'severity' => 'info',
            'title' => 'Нет Cross-Origin-Embedder-Policy',
            'description' => 'Нет COEP на HTTPS 200. Нужен с COOP для isolation; для обычного сайта часто не обязателен.',
            'group' => 'tech',
        ],
        'missing_corp' => [
            'phase' => 'C',
            'severity' => 'info',
            'title' => 'Нет Cross-Origin-Resource-Policy',
            'description' => 'Нет CORP — ресурс не помечает, можно ли его встраивать/читать с чужого сайта; важно вместе с COEP.',
            'group' => 'tech',
        ],
        'missing_charset' => [
            'phase' => 'B',
            'severity' => 'info',
            'title' => 'Нет charset в HTML',
            'description' => 'В документе не найден meta charset / Content-Type charset.',
            'group' => 'tech',
        ],
    ],
];
